### ISSUE TITLE
add @authenticated() decorator

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-authentication#104]
if that's possible. i'll have a try on it

**Comment by doktordirk** [comment]
have other things to do

**Comment by RWOverdijk** [comment]
What would this decorator do?

**Comment by doktordirk** [comment]
prevents execution of the methods if not authorized

**Comment by doktordirk** [comment]
ps: agreed on should throw Error. if fail silently can be an option is left open for now

**Comment by doktordirk** [comment]
had a try, but didn't get past Container.instance 
https://github.com/doktordirk/aurelia-authentication/commit/58874d0da175f039be446f5d96de90f2c6468c27

**Comment by doktordirk** [comment]
RWOverdijk 
Mhm I think I get it
It sounded like a cool feature, but come to think of it it's quite useless
You can easily add a conditional

doktordirk @doktordirk 09:26
yup.
though: 
- no need to inject authService. 
- easy to spot restricted methods
- might play well with permissions

Wesley Overdijk @RWOverdijk 09:40
It might
Mhm something to keep in the issues for now
Just as a reminder
