### ISSUE TITLE
use aurelia logger

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-authentication#105]
with all those deprecated messages it becomes really neccessary

**Comment by RWOverdijk** [comment]
Are there docs on it?

**Comment by doktordirk** [comment]
dunno. i just look at code and aurelia-api docs

**Comment by doktordirk** [comment]
implemented in https://github.com/SpoonX/aurelia-authentication/pull/103/commits/49fe1e0f2bf145e045cfba168750ded70f35e573
