### ISSUE TITLE
legacy references still

### ISSUE THREAD

**Issue by meash-nrel** [SpoonX/aurelia-authentication#109]
Across spoonx libraries you have changed lib references from github:/spoonx/\* to just npm:*

There are still references in /dist/\* sources to 'spoonx/aurelia-api' in this project so it's still loading that old reference as a dependency.

**Comment by RWOverdijk** [comment]
@meash-nrel That _should_ only be on the branch, and there shouldn't be a tag for it yet. If there is, it's our fault and it'll have to be fixed.

**Comment by doktordirk** [comment]
@RWOverdijk dist= new build and we didn't make a new build on master for some time

**Comment by AdamWillden** [comment]
To be extra clear. dist is only updated once there is a release

**Comment by AdamWillden** [comment]
Ahh @doktordirk  beat me

**Comment by RWOverdijk** [comment]
It has to be extremely clear now haha
