### ISSUE TITLE
GitHub installation with SpoonX aurelia-api breaks tests

### ISSUE THREAD

**Issue by MarcScheib** [SpoonX/aurelia-authentication#111]
Hi guys,

installing aurelia-authentication and aurelia-api breaks my tests (not my app). I think this is somehow related to the dependencies. I have the following in package.json:

```
      "aurelia-api": "github:SpoonX/aurelia-api@^2.2.0",
      "aurelia-authentication": "github:SpoonX/aurelia-authentication@^2.1.1",
```

This generates a config.js with three entries:

```
    "github:SpoonX/aurelia-api@2.2.0": {
    "github:SpoonX/aurelia-authentication@2.1.1": {
    "github:spoonx/aurelia-api@2.2.0": {
```

My jspm_packages only has a SpoonX directory. Karma gives me the following error:

```
15 04 2016 19:51:30.411:WARN [web-server]: 404: /base/jspm_packages/github/spoonx/aurelia-api@2.2.0.js
15 04 2016 19:51:30.433:WARN [web-server]: 404: /base/jspm_packages/github/spoonx/aurelia-api@2.2.0/aurelia-api.js
Chrome 49.0.2623 (Windows 8.1 0.0.0) ERROR: 'Potentially unhandled rejection [8] Error: XHR error (404 Not Found) loading http://localhost:9876/base/jspm_packages/github/spoonx/aurelia-api@2.2.0.js
    at error (http://localhost:9876/base/jspm_packages/system.src.js?6536115be64e0ff966e05546f7767676fa7c03d6:1020:16)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:9876/base/jspm_packages/system.src.js?6536115be64e0ff966e05546f7767676fa7c03d6:1028:13)'
```

Any advice? NPM install of auth is not possible at the moment because of some install errors (see https://github.com/SpoonX/aurelia-authentication/issues/81).

**Comment by doktordirk** [comment]
use lower case only for now. but will change very soon to npm anyways

**Comment by doktordirk** [comment]
meaning 
jspm uninstall aurelia-api
jspm i github:spoonx/aurelia-api

**Comment by MarcScheib** [comment]
It seems to be this is not possible. It simply removes to uppercased version but does not install the lowercase.

I tried installing both lowercased which results in the following:
This breaks both, app and tests.

App says: `system.src.js:4597 GET http://localhost:9000/dist/spoonx/aurelia-api.js 404 (Not Found)`
Tests say: `404: /base/jspm_packages/github/SpoonX/aurelia-authentication@2.1.1/aurelia-authentication.js`

**Comment by MarcScheib** [comment]
I could make it work locally by adjusting aurelia-authentication@2.1.1.js when both is installed lowercase:

From

```
define(["github:SpoonX/aurelia-authentication@2.1.1/aurelia-authentication"], function(main) {
  return main;
});
```

to

```
define(["github:spoonx/aurelia-authentication@2.1.1/aurelia-authentication"], function(main) {
  return main;
});
```

TravisCI has no problem with running the tests, it is only locally (cause I am using Win).
