### ISSUE TITLE
redirect_uri for LinkedIn need to be encoded 

### ISSUE THREAD

**Issue by 0xSalman** [SpoonX/aurelia-authentication#113]
Hey guys,

So LinkedIn fails to authorize if `redirect_uri` value is not encoded. I am getting around it by overriding `redirectUri` property in the configuration file.  For example

```
redirectUri: encodeURI(window.location.origin || window.location.protocol + '//' + window.location.host)
```

You guys may want to support it by default

**Comment by RWOverdijk** [comment]
@msalman86 Excellent suggestion. I actually think this should be default behavior, seeing how it's a query string argument. Mind opening up a PR for this?

**Comment by 0xSalman** [comment]
Sure, will do
