### ISSUE TITLE
aurelia-authentication-samples???

### ISSUE THREAD

**Issue by sethom** [SpoonX/aurelia-authentication#114]
In the Quick Start (http://aurelia-authentication.spoonx.org/Quick%20start.html) in the "Provide a UI for a logon, Signup and Profile" section it states  "See aurelia-authentication-samples for more details."

Where's aurelia-authentication-samples located? Is there a working sample application to download?

**Comment by RWOverdijk** [comment]
@sethom Nice catch.

I believe you can find an example here: https://github.com/doktordirk/aurelia-authentication-loopback-sample @doktordirk made it

**Comment by sethom** [comment]
Thanks RWOverdijk..   That's a big help.

Btw, is it possible to use aurelia-authentication with Asp.net WebApi just as easily as with Loopback? Are there some differences I need to keep in mind? I haven't found any discussions about aurelia-authentication or aurelia-auth in relation to Asp.net WebApi yet.

**Comment by doktordirk** [comment]
since auth/authentication is the same as satellizer for angular maybe look for Asp.net WebAp+ angular (or +satellizer)

**Comment by sethom** [comment]
Oh yeah. It looks like Satellizer started supporting Asp.net webapi as May last year: https://github.com/sahat/satellizer/issues/219

**Comment by doktordirk** [comment]
https://github.com/SpoonX/swan-example-client
