### ISSUE TITLE
npm install for webpack fails

### ISSUE THREAD

**Issue by iBelieve** [SpoonX/aurelia-authentication#116]
I have a webpack-based aurelia project. I installed aurelia-authentication using `npm i aurelia-authentication`. 

WebPack (via `npm run dev`) complains about not being able to find `spoonx/aurelia-api`:

```
ERROR in ./~/aurelia-authentication/dist/commonjs/aurelia-authentication.js
Module not found: Error: Cannot resolve module 'spoonx/aurelia-api' in /Users/mspencer/Developer/Lelander/skills/webapp/node_modules/aurelia-authentication/dist/commonjs
 @ ./~/aurelia-authentication/dist/commonjs/aurelia-authentication.js 12:18-47

ERROR in ./~/aurelia-authentication/dist/commonjs/app.fetch-httpClient.config.js
Module not found: Error: Cannot resolve module 'spoonx/aurelia-api' in /Users/mspencer/Developer/Lelander/skills/webapp/node_modules/aurelia-authentication/dist/commonjs
 @ ./~/aurelia-authentication/dist/commonjs/app.fetch-httpClient.config.js 22:18-47
```

**Comment by doktordirk** [comment]
we are just about to release a webpack supported version. 

meanwhile you can try: 

npm i github:spoonx/aurelia-api#dev
npm i github:spoonx/aurelia-authentication#dev

**Comment by iBelieve** [comment]
Thanks for the quick response!

The first command works, but unfortunately the second fails:

```
$ npm i github:spoonx/aurelia-authentication#dev
/path/to/project
└── aurelia-authentication@2.1.0  invalid (git://github.com/spoonx/aurelia-authentication.git#748ec34fbde9ba0342eac31057165bc1719c910a)
```

**Comment by doktordirk** [comment]
hmm. worked for me. copied again from console:

npm i github:spoonx/aurelia-authentication#dev --save

but i found another problem anyways (with the ./authfilter)

ps forgot to add the --save
pps: or try to add to package.json dependencies sectioin:

"aurelia-api": "github:spoonx/aurelia-api#dev",
"aurelia-authentication": "github:spoonx/aurelia-authentication#dev",

but probably fill fails with that authfilter. in case you wanna play, cou can remove the authfilter entries in aurelia-authentication/dist/commonjs/aurelia-authentication.js

**Comment by doktordirk** [comment]
seems it can be solved by making  authFilter an optional global resource

https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/428 has info for that

or better:
https://gist.github.com/valichek/5dc7c1e11ed39a82df83913df465cb50

**Comment by doktordirk** [comment]
sortof working version. might be as good as it gets:

https://github.com/doktordirk/aurelia-authentication-loopback-sample/tree/master/client-wp

**Comment by doktordirk** [comment]
updated my sample. to be considered solved

**Comment by iBelieve** [comment]
Thanks! Everything seems to be working correctly now.
