### ISSUE TITLE
Can't set request header to application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by robinchesterman** [SpoonX/aurelia-authentication#14]
I think the OAuth2 spec prefers that login token requests are sent with Content-Type: application/x-www-form-urlencoded - often with a grant_type value as well.

I can't see an easy way to do this with aurelia-auth, but I may be missing something.

I'm trying to call a .Net Web Api with OWIN for all the auth stuff, and I don't have a lot of flexibility on the type of requests that will be accepted.

**Comment by robinchesterman** [comment]
Sorry, this probably isn't an "issue" - I'll find you on gitter.

**Comment by RWOverdijk** [comment]
Interesting case. Let's talk :) https://gitter.im/SpoonX/Dev
