### ISSUE TITLE
Suggestion: support dotted notation for accessTokenProp (and refreshtoken)

### ISSUE THREAD

**Issue by apawsey** [SpoonX/aurelia-authentication#143]
Just to make the config slightly easier, allow the accessTokenProp to be specified as (examples):
- 'accessToken' (on root)
- 'tokenResponse.accessToken' (in sub-object)
- 'tokenResponse.access.tokenValue' (and so on...)

Just a suggestion :)

**Comment by doktordirk** [comment]
@apawsey happy with that https://github.com/SpoonX/aurelia-authentication/issues/148 ?
