### ISSUE TITLE
Feature Request: Redirect to original page after successful login

### ISSUE THREAD

**Issue by apawsey** [SpoonX/aurelia-authentication#144]
So the gist here is if I click a link, and it turns out for whatever reason I'm not/no longer authenticated, I get redirected to the login... fine. But when I login, I get redirected back to home or wherever that is statically configured in my authentication settings.  It would be good if we could support redirecting back to the original page I wanted to reach.

I actually wanted to submit a PR for this, I started fiddling, and essentially I can make it work... but to make it right, I need to understand a little more about the getAllInstructions() method.  How/why would there be multiple instructions in one navigation?  If you guys can give the help with this context, I'll happily submit my PR for this.

**Comment by doktordirk** [comment]
that's definitely a missing feature. so a PR would be great
http://aurelia.io/docs.html#/aurelia/router/1.0.0-beta.1.2.2/doc/api/class/NavigationInstruction
i guess, one gets the route from the routingContext, calls new Redirect(loginRoute+&oldRoute) which is use in authService.login or so

**Comment by RWOverdijk** [comment]
👍

**Comment by apawsey** [comment]
Yeah I looked at the documentation, and yes that's basically the approach I took.  Take the intended route, encode it as a querystring parameter, and move on to login.  Then login if it sees that querystring, redirects back to that, instead of the default route.

As I said though, I don't understand how or why there can be multiple instructions within the context.  From the docs:
getAllInstructions() : Array
Gets an array containing this instruction and all child instructions for the current navigation.

Do you guys know or have an example of what the child instructions might be?  I don't want to do this change, and find it only works in 50% of situations for example.

**Comment by doktordirk** [comment]
it's the route to the view like /user/private. so the main route user might have the auth flag, or the child route private might have the auth flag. hence each part of the route needs to be checked. 

however, it's not much of your concern as you just can take routingContext.fragment + '?' + routingContext.queryString

**Comment by apawsey** [comment]
guys, not sure if I'm being stupid, but looking for any key build instructions, tests, etc?  Just want to make sure I follow the correct path for submitting the PR.

**Comment by doktordirk** [comment]
There is the contributing.md. Otherwise I usually just follow what others hAve been doing. But don't worry too much. As for proper, i dont know how to in this case as Karma complains after the full page reload after login anyways

**Comment by RWOverdijk** [comment]
@apawsey Not stupid at all! Asking questions is good :) Like @doktordirk pointed out you could take a look at our [contributing guide (link)](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md). For other questions I'd like to point you to our [gitter channel (link)](https://gitter.im/SpoonX/Dev). I hope this helps you help us :)

**Comment by apawsey** [comment]
No I've read then contributing guide etc, and I get the commit messages, that stuff.  I was looking for build instructions, like "We use JSPM" or "We hate jspm and will instantly ban you from contributing if you type those letters into your console" :)  Will jump on Gitter though, good point.

**Comment by RWOverdijk** [comment]
To bump this: we use jspm and we support webpack. While developing, you'll probably want to use a linked clone locally. When making your commits, leave out the build (so no dist filed). Those are generated per-release using the gulp task `prepare-release`.

**Comment by mateuszdw** [comment]
Hi, 
If you need hack for this functionality, you can create custom PipelineStep and insert url before login to this.auth.authentication.config.loginRedirect. If you need you can clear it after successful login.

```javascript
...
config.addPipelineStep('authorize', BeforeRedirectToLoginStep); // this step store url before redirect to login page
config.addPipelineStep('authorize', AuthenticateStep); // Add a route filter so only authenticated uses are authorized to access some routes
...
@inject(AuthService)
class BeforeRedirectToLoginStep {
  constructor(auth) {
    this.auth = auth;
  }
  run(navigationInstruction, next) {
    // store url if contain weblib/
    let navigationInstructions = navigationInstruction.getAllInstructions()
    if (navigationInstructions.some(i => i.fragment.indexOf('weblib/') !== -1)){
      this.auth.authentication.config.loginRedirect = '#' + navigationInstructions[0].fragment
    }
    return next();
  }
}
```
