### ISSUE TITLE
Feature Request: add support for auth0-lock authentication

### ISSUE THREAD

**Issue by pfurini** [SpoonX/aurelia-authentication#146]
Hi
I just implemented auth0-lock integration in my fork, to use in my latest app. This is the commit:
https://github.com/nexbit/aurelia-authentication/commit/17ed43a99ac4b514c2e6a024190cb38f35f8d147

It is a bit rough, and I don't know how to implement proper testing for this, but at least it works..

Key points:
- It predates the **oauthType** config property, checking if it is equal to _auth0-lock_ to use the auth0Lock.js provider. It's a bit hacky, but it'd be better if that property was named _type_ like it used to be in the past..
- It expects a global **Auth0Lock** class defined. One should load the _lock-9.1.min.js_ script directly in index.html
- It supports only the _token_ responseType
- Only tested in _popup_ mode (speaking of lock options), probably not working in redirect mode, but it should be trivial to adjust

Let me know if anyone is interested in merging this, and what can be done to improve it (especially how to implement tests).

Thx

**UPDATE**: I changed the commit, the old one was wrong. The relevant files are only auth0Lock.js (added) and authentication.js (changed).

**Comment by doktordirk** [comment]
Re type: i only changed it to quickly copy changes from sahat. But you have a point with using type

**Comment by pfurini** [comment]
Ok.. maybe we can introduce a new externalProvider config property, 
and let the oauthType to be used only for existing oauth providers.

The externalProvider property should accept a string that is the name 
used to register the provider class with the aurelia default DI 
container. For example my auth0Lock provider could be moved to an 
external plugin that simply register the class with the DI container, 
and your code then loads it.

What do u think?

doktordirk wrote:

**Comment by doktordirk** [comment]
generally having better IoC there would have been nice indeed. for now, i think it's fine as you did it i think. mind throwing together a 'proper' PR? would be a great addition imho

**Comment by pfurini** [comment]
What about testing? The PR would completely miss them if I open it now.. I don't know if the auth0 guys have some service mock ready to use, but now I don't have enough time to find or implement it in testing code.

**Comment by doktordirk** [comment]
alas we don't test the actual services right now anyways. so i guess just copy the oath2 test and adapt it to your needs

**Comment by pfurini** [comment]
Resolved by https://github.com/SpoonX/aurelia-authentication/commit/f8aeef58108708707ffda06cd6c2ce78707adfd2
