### ISSUE TITLE
Feature Request: rename `AuthorizeStep` to `AuthenticateStep`

### ISSUE THREAD

**Issue by pfurini** [SpoonX/aurelia-authentication#156]
The `AuthorizeStep` class does check for _authentication_ status and has nothing to do with authorization. Thus the name `AuthenticateStep` is more aligned with its scope.

But the main reason for renaming is to let a future authorisation plugin use the `AuthorizeStep` name for its pipeline step class.

**Comment by doktordirk** [comment]
i agree. we can keep a (deprecated) AuthorizeStep without conflict (mostly).

on a general note: we wanna stay like 100% BC to vanBlandels for the time being for ease of switching over

**Comment by pfurini** [comment]
Ok for BC.. But then I should call my step `RealAuthorizeStep`?? 😲

**Comment by doktordirk** [comment]
unless one/you imports {AuthorizeStep}  from 'authelia-authentication'... there's no conflict and in that case one could use import {AuthorizeStep as OldAuthorizeStep] from 'authelia-authentication'.
(resp import {AuthorizeStep as RealAuthorizeStep} from 'aurelia-acl';)

**Comment by pfurini** [comment]
Well that will be common case, unfortunately, cause one will add first 
an authentication step and then an authorization one..
So we will end up with aliasing by default, something like

import {AuthorizeStep as AuthenticateStep] from 'authelia-authentication';
import {AuthorizeStep] from 'authelia-whateverwenamedit';

but we deal with compromises every day, so that's fine if properly 
documented

doktordirk wrote:

**Comment by pfurini** [comment]
Discard my last comment.. we said you'll add a new AuthenticationStep class anyway, so what I said is garbage 😖

**Comment by doktordirk** [comment]
hehe, i started to get lost. perfect then
