### ISSUE TITLE
Seems the facebook auth popup doesn't close when auth completes

### ISSUE THREAD

**Issue by icanhasjonas** [SpoonX/aurelia-authentication#173]
Affects `3.0.0-rc3` and works as expected in `3.0.0-rc2`

**Comment by icanhasjonas** [comment]
After facebook auth the popup remains open and redirected to `http://localhost:3000/_=_?code=<oauth code>`

Nothing special in my configuration I spuspect:

``` js
{
    baseUrl: '/api',
    providers: {
        facebook: {
            clientId: facebookId,
            scope: facebookScopes
        }
    }
}
```

**Comment by doktordirk** [comment]
i know. facebook changed that. PR is on the way

**Comment by doktordirk** [comment]
@icanhasjonas i made a dev build with a fix. not 100% if it works for you. hope so. you can try with 
`jspm i aurelia-authentication=github:spoonx/aurelia-authentication@dev`
will need aurelia-api@rc3
