### ISSUE TITLE
IE9/IE10 crash in AuthService.js

### ISSUE THREAD

**Issue by cb-fred** [SpoonX/aurelia-authentication#185]
Hi,

We've encountered an issue in IE<=10 with Aurelia-Authentication (version 1.1.2), Working fine with Edge, and we've included all the necessary polyfills: fetch.js, bluebird.js, etc...

In line 31 of AuthService.js, config is undefined:

```
this.auth = auth;
this.oAuth1 = oAuth1;
this.oAuth2 = oAuth2;
this.config = config.current;   // config is undefined.
this.client = this.config.client;
```

Which causes an obvious problem. This code is called during the instanciation
of our Authentication class, whose code follows: 

```
import {inject} from 'aurelia-dependency-injection';
import {AuthService} from 'spoonx/aurelia-authentication';
import {Endpoint} from 'spoonx/aurelia-api';

@inject(Endpoint.of('codabox-api'))
export class CodaboxAuthService extends AuthService {
  constructor(codaboxApi, ...args){
    super(...args);   // crashes here.
    this.codaboxApi = codaboxApi;
  }
  ...
}
```

Any idea ?

**Comment by doktordirk** [comment]
in that version current is a getter. if you can try to use t eobject directly aka `this.config = config._current`

**Comment by cb-fred** [comment]
Well, the problem is that `config` is undefined. `config.current` is trying to access a field from an `undefined` reference, thus the crash.

**Comment by doktordirk** [comment]
hang on a little, i think it'll be fixed in the next version.

**Comment by doktordirk** [comment]
you need to inject all again when extending i'm sure

@inject(Endpoint.of('codabox-api'), Authentication, OAuth1, OAuth2, BaseConfig);

**Comment by doktordirk** [comment]
> This is super urgent. A workaround is:

class Foo extends Bar {
  constructor () {
    super()
    Bar.call(this)
  }
}
Note that this calls the parent constructor twice in other browsers, so make sure your parent constructor does nothing too complex (which it shouldn't anyway)

**Comment by doktordirk** [comment]
or

I've actually just found something that fixed this problem for me. There's an option called loose for babel-plugin-transform-es2015-classes, that makes it work on IE <= 10. I don't know if on babel 5 this was turned on by default or if the code always worked on older browsers, but it seems like setting this option is what's required now, it all works perfectly as before.

You basically just need to explicitly pass the plugin with the option, instead of just using the es2015 preset, like this:

plugins: [['transform-es2015-classes', {loose: true}]]
Seems like this isn't a bug then, but I still think this should be better documented so people know what to do to make babel 6 compiled code work on all browsers.

**Comment by cb-fred** [comment]
Ok, thanks for your investigation, I will try this and confirm that it works on my side.

**Comment by cb-fred** [comment]
Hi, thanks for looking it up, but I can't get it to work. It builds all-right, but it's still not working in IE. 
I'm not sure I am doing things right as I am not familiar with either aurelia nor babel. Maybe you can
point me at some mistake ?  

Here's my `build/babel-options.js`

```
var path = require('path');
var paths = require('./paths');

exports.base = function() {
  return {
    filename: '',
    filenameRelative: '',
    sourceMap: true,
    sourceRoot: '',
    moduleRoot: path.resolve('src').replace(/\\/g, '/'),
    moduleIds: false,
    comments: false,
    compact: false,
    code: true,
    presets: [ 'es2015-loose', 'stage-1'],
    plugins: [
      'syntax-flow',
      'transform-decorators-legacy',
      'transform-flow-strip-types',
      'transform-class-properties',
      ['transform-es2015-classes', {loose: true}]
    ]
  };
};

exports.commonjs = function() {
  var options = exports.base();
  options.plugins.push('transform-es2015-modules-commonjs');
  return options;
};

exports.amd = function() {
  var options = exports.base();
  options.plugins.push('transform-es2015-modules-amd');
  return options;
};

exports.system = function() {
  var options = exports.base();
  options.plugins.push('transform-es2015-modules-systemjs');
  return options;
};

exports.es2015 = function() {
  var options = exports.base();
  options.presets = ['stage-1'];
  return options;
};
```

And I installed the following npm packages: 

```
 +    "babel-plugin-transform-class-properties": "^6.9.1",
 +    "babel-plugin-transform-es2015-classes": "^6.9.0",
```

**Comment by doktordirk** [comment]
without the loose it seems to work for me

``` js
presets: [ 'es2015-loose', 'stage-1'],
    plugins: [
      'syntax-flow',
      'transform-decorators-legacy',
      'transform-flow-strip-types',
      'transform-class-properties',
      'transform-es2015-classes'
    ]
```

**Comment by cb-fred** [comment]
Thanks !
This fixed the issue. 
Unfortunately there were lots of other IE issues waiting behind ... but that's none of your concern :)

**Comment by doktordirk** [comment]
oho good luck then
