### ISSUE TITLE
how to correctly bundle aurelia-authentication into project ?

### ISSUE THREAD

**Issue by k2s** [SpoonX/aurelia-authentication#189]
using now 3.0.0-rc4

to get it work I have to add to my projects `bundles.js` file:

```
        "aurelia-authentication",
        "aurelia-authentication/authFilterValueConverter.js",
        "aurelia-authentication/authenticatedValueConverter.js",
        "aurelia-authentication/authenticatedFilterValueConverter.js",
```

whould expect that `aurelia-authentication` should be enough

**Comment by RWOverdijk** [comment]
@doktordirk I don't have to add these three for my bundling. Didn't you fiddle with this?

**Comment by k2s** [comment]
had to add it today after I updated to 3.0.0-rc4 with jspm

**Comment by RWOverdijk** [comment]
Ah yeah, I think those are new then.

**Comment by doktordirk** [comment]
didn't i remove
        "aurelia-authentication/authenticatedValueConverter.js",
        "aurelia-authentication/authenticatedFilterValueConverter.js",
since i could find use for those yet?

**Comment by doktordirk** [comment]
and the first    "aurelia-authentication/authFilterValueConverter.js", should have been in. hmm

**Comment by doktordirk** [comment]
hmm, something did get mixed while i made the PRs or while merging. it's a little inconsistent now, but no big deal

**Comment by doktordirk** [comment]
ok, so 'authFilterValueConverter.js' should still be bundles 'automatically'. the other two are still there and made global if desired (default), but not bundled 'automatically'. i'd say, we just leave it as it is as it's perfectly BC

**Comment by RWOverdijk** [comment]
@doktordirk The issue is with bundling. Perhaps they're being required somewhere anyway?

@k2s What's the issue for you exactly? Does it ask for those files, but it can't find them?

**Comment by k2s** [comment]
in my minified bundle I see `this.globalValueConverters=["authFilterValueConverter","authenticatedFilterValueConverter","authenticatedValueConverter"]`

this has to be a reason why it is loaded in browser. I don't reference the modules in other places.

**Comment by RWOverdijk** [comment]
So it defaults to all. @doktordirk In that case it's not BC and it does make sense that it breaks, right?

**Comment by doktordirk** [comment]
@RWOverdijk right, the baseConfig defaults need fixing
@k2s add to your authConfig
globalValueConverters: ["authFilterValueConverter"],

**Comment by k2s** [comment]
thank you for your help !
