### ISSUE TITLE
Typo in aurelia-authentication.d.ts causing tsc error.

### ISSUE THREAD

**Issue by erikvullings** [SpoonX/aurelia-authentication#192]
In [aurelia-authentication.d.ts](https://github.com/SpoonX/aurelia-authentication/blob/master/dist/system/aurelia-authentication.d.ts), line 444, current is defined again (as in line 438), causing `tsc` to throw a duplicate error when compiling. Please remove either one.

**Comment by doktordirk** [comment]
oh
