### ISSUE TITLE
What to do with: WARN [authentication] AuthorizeStep is deprecated. Use AuthenticationStep instead.

### ISSUE THREAD

**Issue by erikvullings** [SpoonX/aurelia-authentication#193]
In the console, I see this warning: however, when I search the code, the only time I encounter AuthorizationStep is in the LogManager. So, what is the idea behind this? Am I missing something? Or can we expect an update and example of how to use AuthorizationStep? Thanks...

**Comment by doktordirk** [comment]
you probably use AuthorizeStep in your app.ts as 
   config.addPipelineStep('authorize', AuthorizeStep); // Add a route filter to the authorize extensibility point.

to avoid misunderstanding authorization with authentication, it was suggested we replace it with AuthenticateStep, so
config.addPipelineStep('authorize', AuthenticateStep); // aka only authenticated users are authorized to use some routes

**Comment by doktordirk** [comment]
ps: the sample in quick-start http://aurelia-authentication.spoonx.org/Quick%20start.html got updated

**Comment by doktordirk** [comment]
todo: add a what's new page

**Comment by erikvullings** [comment]
Thanks! This solved it for me.
