### ISSUE TITLE
Exporting/bundling aurelia-authentication issue

### ISSUE THREAD

**Issue by erikvullings** [SpoonX/aurelia-authentication#196]
I'm new to bundling, but I am using `aurelia-authentication` with the (latest version of the) skeleton-typescript. When I wish to include `aurelia-api`, I just need to add it to my `bundles.js` and everything works fine. However, adding `aurelia-authentication` isn't enough, and I get errors about missing files.

``` javascript
        'jspm_packages/npm/aurelia-authentication@3.0.0-rc4/aurelia-authentication.js',
        'jspm_packages/npm/aurelia-authentication@3.0.0-rc4/authenticatedFilterValueConverter.js',
        'jspm_packages/npm/aurelia-authentication@3.0.0-rc4/authenticatedValueConverter.js',
        'jspm_packages/npm/aurelia-authentication@3.0.0-rc4/authFilterValueConverter.js',
```

Just to clarify, unbundled, everything works fine, but after running `gulp export` I get those errors. Am I missing something, or is there an easier version to include it in the bundle?

**Comment by RWOverdijk** [comment]
@erikvullings I know that @doktordirk fixed this, partially. I don't think this is in a release yet. We'll be making a new release the coming days, sorry for the inconvenience.

**Comment by doktordirk** [comment]
ps: aurelia typescript setting is changing, so not that straight forward to test there currently

**Comment by doktordirk** [comment]
meanwhile on rc4, adding 
`globalValueConverters: ['authFilterValueConverter'],`
to your authConfig and sticking to the 'old' authFilter should do the trick

**Comment by erikvullings** [comment]
Hmm, that didn't do the trick for me. 
When do you expect to have a final version finished?

**Comment by doktordirk** [comment]
try rc5/master on github: `jspm i aurelia-authentication=github:spoonx/aurelia-authentication@master`
that one is hopefully the final

**Comment by doktordirk** [comment]
should be solved when following the install instructions
