### ISSUE TITLE
 Duplicate identifier 'current'.

### ISSUE THREAD

**Issue by manyrootsofallevil** [SpoonX/aurelia-authentication#199]
I just tried to build my aurelia based project and I get the following error:

> [21:22:17] Finished 'build-html' after 109 ms
> "C:/Checkout/Assessment/src/Assessment/wwwroot/jspm_packages/npm/aurelia-authentication@3.0.0-rc4/aurelia-authentication.d.ts(438,5): Duplicate identifier 'current'."
> "C:/Checkout/Assessment/src/Assessment/wwwroot/jspm_packages/npm/aurelia-authentication@3.0.0-rc4/aurelia-authentication.d.ts(444,5): Duplicate identifier 'current'."

This seemed to start occurring after I did install of all the packages with jspm.

Had a perusal through the code on the repo and it seems that the issue was fixed a few days ago but not sure whether the jspm package hasn't been updated or something else is going on here

For the record, the baseConfig class does have two properties called current and manually removing one does fix the issue, but this fix is of no use on hosted build server.

Any ideas?

**Comment by doktordirk** [comment]
That.s fixed in the next Release. try rc5/master on github: jspm i aurelia-authentication=github:spoonx/aurelia-authentication@master
