### ISSUE TITLE
Fix redirect (electron)

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/aurelia-authentication#2]
You know

**Comment by mateuszdw** [comment]
Hello RWOverdijk,

do you have any working example of aurelia-authentication and electron?

When I use electron this statement breaks 
```
if (this.popupWindow.location.host ===  PLATFORM.global.document.location.host
            && (this.popupWindow.location.search || this.popupWindow.location.hash)) {
```

PLATFORM.global.document.location.host return null
this.popupWindow.location.host return undefined

also the electron popup window object is BrowserWindowProxy and it not has hash function in this.popupWindow.location.hash

Thanks

**Comment by RWOverdijk** [comment]
Hello @mateuszdw,

I don't have such example. I'm not sure how that would work because it's not really a browser. I do want this to work, so if you know more about it I'd love to hear it so we can improve the module.

**Comment by mateuszdw** [comment]
No problem. I think I worked it out on electron. Here is my fork
```
jspm install aurelia-authentication=github:mateuszdw/aurelia-authentication@master
```
Critical changes are in these lines 
https://github.com/mateuszdw/aurelia-authentication/commit/796f4f4a31af9a82193258a175882e11b03069a5#diff-57de96bf5b2cda8ece0c58273e1f3293R70
https://github.com/mateuszdw/aurelia-authentication/commit/796f4f4a31af9a82193258a175882e11b03069a5#diff-8ebce89d9c7de205daa19cd9eaf5f21aR79

I dont know if I build my fork package correctly. I used only `gulp build`.

When integrating app with electron we need set up redirectUri in aurelia-authentication config 
to something like `redirectUri: 'http://localhost:3000/auth/blankcallback'`
So on server side we need to create blankcallback which return simple 200 OK.
And from now on all should just work.

For server side examples you should go to satellizer repo https://github.com/sahat/satellizer/tree/master/examples/server

**Comment by RWOverdijk** [comment]
@VMBindraban could you look at these changes and implement them?

**Comment by mateuszdw** [comment]
What I didn't do in my fork but I recommend, is to extend this condition by "electron" platform somewhere along these lines https://github.com/SpoonX/aurelia-authentication/blob/master/src/oAuth2.js#L68

**Comment by RWOverdijk** [comment]
@mateuszdw Thanks. CC @VMBindraban
