### ISSUE TITLE
Bug in aurelia-authentication.js configure() ?

### ISSUE THREAD

**Issue by jeremy-holt** [SpoonX/aurelia-authentication#201]
There seems to be a bug at function configure().

I think it should be `_aureliaPal.PLATFORM.global.location.origin`

```
 function configure(aurelia, config) {
    if (!_aureliaPal.PLATFORM.location.origin) {
      _aureliaPal.PLATFORM.location.origin = _aureliaPal.PLATFORM.location.protocol + '//' + _aureliaPal.PLATFORM.location.hostname + (_aureliaPal.PLATFORM.location.port ? ':' + _aureliaPal.PLATFORM.location.port : '');
    }

.....
```

**Comment by doktordirk** [comment]
PLATFORM has location http://aurelia.io/docs.html#/aurelia/pal/1.0.0-beta.1.2.2/doc/api/interface/Platform

did you have any problems or did you review the code?

**Comment by jeremy-holt** [comment]
Yes I had a problem...

I added the plugin and just followed the documentation for setting up configure. The code fails at `baseConfig.configure(authConfig)`

```
 aurelia.use
    .standardConfiguration()
    .developmentLogging();
    .plugin("aurelia-authentication", baseConfig => {
      baseConfig.configure(authConfig);
   });
```

**Comment by jeremy-holt** [comment]
I just looked at PLATFORM in the Chrome debugger - it has PLATFORM.global.location which is what led me to file the bug report.

This is using the latest version of skeleton-typescript downloaded this morning

**Comment by doktordirk** [comment]
If have trouble myself with the new Aurelia updates. I fear it is better for us to wait till they have settled again

**Comment by doktordirk** [comment]
What is the error message btw?

**Comment by jeremy-holt** [comment]
I scrapped the code, but it was something like aureliaPal.PLATFORM.location.origin not a reference, where "location" does _not_ exist on PLATFORM. Like I said "location" is a property of PLATFORM.global (well according to the Chrome debugger).

Just put the initialization code into the skeleton-typescript `main.js`

I tell you - aurelia is getting almost as bad as angular 1.4xx. Every damn day something changes. I've been farting around for nearly a week trying to start a new project. I would like to do it in typescript/webpack - but the current version of the skeleton doesn't understand plugins!

The default skeleton-typescript throws loads of d.ts errors.

I started to use the old aurelia-auth until I came across aurelia-authentication. But I can't even get the simplest thing to work - i.e. just the basic configuration.

I tried Auth0 but their code doesn't seem to work with Typescript and ES6.

It's all very very frustrating.

Sorry for sounding off like this - I think aurelia is brilliant - I've written some really big apps in it - but in the last few weeks it seems to have gone off the rails!

I understand that they are getting close to release and are trying to make it easier for newbies (me included), but have you seen the webpack.config.js in the skeleton-webpack?? WTF!

Oh - the joys of being at the bleeding edge :)

**Comment by doktordirk** [comment]
doesn't make sense still. 
in: pal-browser/platfom.js
`location: window.location,`
something is wrong with you setup or the current skeleton. but as you said, with the current push towards aurelia-cli and a pre-release, it's all really messed up now

**Comment by jeremy-holt** [comment]
<img width="1101" alt="sshot-1" src="https://cloud.githubusercontent.com/assets/2135027/16178253/4b353ce8-3619-11e6-8179-526ef6153454.png">

1) fresh install of skeleton-typscript
2) `main.ts`

```
import 'bootstrap';
import {Aurelia} from 'aurelia-framework';
import authConfig from "./authConfig";

export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin("aurelia-authentication",baseConfig=>{
      baseConfig.configure(authConfig);
    });

  //Uncomment the line below to enable animation.
  //aurelia.use.plugin('aurelia-animator-css');

  //Anyone wanting to use HTMLImports to load views, will need to install the following plugin.
  //aurelia.use.plugin('aurelia-html-import-template-loader')

  aurelia.start().then(() => aurelia.setRoot());
}
```
1. PLATFORM does not have a `location` property!

Hey - please understand I'm not "having a go". I would really like to use aurelia-authentication - from what I gather it takes all the hard work away from me. AND I fully appreciate that the current seleton-typescript doesn't work out of the box. 

gulp watch throws up a load of d.ts errors

**Comment by doktordirk** [comment]
what i wanted to say is, that it is quite likely that the mess-up aurelia  updates and skeleton cause that error. maybe try my sample which is based on an older skeleton and play with that for a while until aurelia's current updates have settle a bit 
https://github.com/doktordirk/aurelia-authentication-loopback-sample/tree/master/client-ts

ps: aurelia-pal was the first one that broke in the current updates

**Comment by jeremy-holt** [comment]
just out of curiousity is this the "approved" authentication app?

ok - will try the sample

**Comment by doktordirk** [comment]
approved? what you mean? i guess the most official sample would be https://github.com/SpoonX/swan-example-client , but i prefer simple ones, and separate ones for each feature.
