### ISSUE TITLE
What is the proper way to use the plugin?

### ISSUE THREAD

**Issue by oteuan** [SpoonX/aurelia-authentication#203]
Hi,

I am trying to have the plugin working with OpenIdConnectServer. I must be missing something in the configuration (and probably somewhere else) to set properly the way of doing the login POST to get the authService properly authenticated. It can be seen in the Authorisation.ts file the 2 login methods: login() and loginCustom(). Ideally I would like to use the 1st one but at this moment I am using the 2nd one.
Can you please advise?

Thanks!

[aurelia-authentication.zip](https://github.com/SpoonX/aurelia-authentication/files/327445/aurelia-authentication.zip)

**Comment by RWOverdijk** [comment]
Could you perhaps post a snippet of the code (inline or in a gist) in stead of uploading a zip? Also, this kind of question is probably best to ask in our gitter channel :) https://gitter.im/SpoonX/Dev

**Comment by oteuan** [comment]
Thanks Wesley, just done it in https://gist.github.com/oteuan :)

**Comment by doktordirk** [comment]
which version of authentication and api you are using?

**Comment by oteuan** [comment]
Hi,

I wasn't using aurelia-api at first as read it was not needed. After, I plugged it in (version 3.0.0-rc4) but as it did not work i reverted it back. I have updated my gist adding authConfigAureliaApi and the mainAureliaApi files I used at that time for aurelia-api.

Thanks!

**Comment by doktordirk** [comment]
ähm, so is it solved?

**Comment by oteuan** [comment]
hahaha
No, it is not. Let me explain myself a bit better. The process went like:
1. I used the aurelia-authentication plugin so I was using the original files I put in my gist calling the login() method in the authorisation.ts
2. As it didn't work, I read about aurelia-api and I applied it using the authConfigAureliaApi.ts and the mainAureliaApi.ts instead.
3. I still was getting a 401 Unauthorized response so i reverted my changes using Aurelia-Api and I put in place my own login method (loginCustom) doing the POST and setting the authService manually. 

Hoope this makes sense ;)

**Comment by doktordirk** [comment]
@oteuan ah, i forgot. this still valid?

**Comment by oteuan** [comment]
Hi,

No worries.
Yes I am still having this issue. The work-around is what I have at this moment (loginCustom). We are on "aurelia-authentication": "^3.0.0-rc5" at this moment.

Thanks.

**Comment by doktordirk** [comment]
should work. only thing might be Content-Type vs eg content-type. 
else try again to update aurelia-api and authentication. maybe it magically helps
