### ISSUE TITLE
error with rc 5

### ISSUE THREAD

**Issue by vinny-Jo** [SpoonX/aurelia-authentication#206]
I am using aurelia-authentication with nodejs+Webpack+npm and kestrel. webpack resolver is failing:
**"Cannot find module './aurelia-authentication/authFilterValueConverter".**
**INFO [authentication] Add globalResources value-converter: authFilterValueConverter.**

also when I am trying to add aurelia-authentication to **typings**, 
typings install npm:aurelia-authentication --global --save
typings WARN badlocation "github:aurelia/pal" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/pal" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/pal" is mutable and may change, consider specifying a commit hash
typings WARN badlocation "github:aurelia/pal" is mutable and may change, consider specifying a commit hash
typings ERR! message Unable to read typings for "extend". The author of "aurelia-authentication" needs to check the entry paths in "package.json" are up to date
typings ERR! caused by ENOENT: no such file or directory, open 'C:\PHMG.ProspX\PHMG.ProspX.UI\node_modules\extend\index.d.ts'

typings ERR! system Windows_NT 6.3.9600
typings ERR! node -v v6.2.0
typings ERR! typings -v 1.3.1

**Comment by doktordirk** [comment]
i think it was
typings i npm~extend --global

**Comment by vinny-Jo** [comment]
tried 
typings install npm:aurelia-authentication --global --save
Please could you provide the right syntax
typings install npm:aurelia-authentication -npm~extend --global --save
typings install npm:aurelia-authentication ~extend --global --save
typings install npm~aurelia-authentication --global --save
typings install npm:aurelia-authentication --npm~extend --global --save
**same errors**

typings -npm~extend --global --save
**command not recognized**

**Comment by vinny-Jo** [comment]
I am using aurelia-authentication with nodejs+Webpack+npm and kestrel. webpack resolver is failing:
"Cannot find module './aurelia-authentication/authFilterValueConverter".
INFO [authentication] Add globalResources value-converter: authFilterValueConverter.

**Comment by doktordirk** [comment]
the one for authenticaion is currently still hidden in the dist folder. so should be

`typings i github:spoonx/aurelia-authentication/dist/commonjs/aurelia-authentication.d.ts`

**Comment by doktordirk** [comment]
for extend
`typings i npm~extend`
worked for me

**Comment by doktordirk** [comment]
anyways, usually try eg
`typings search extend`
to search for typings

**Comment by vinny-Jo** [comment]
the following line is working
typings i npm:aurelia-authentication/dist/commonjs/aurelia-authentication.d.ts --global --save
aurelia-authentication
└── (No dependencies)

**Comment by vinny-Jo** [comment]
Webpack resolver is failing:
"Cannot find module './aurelia-authentication/authFilterValueConverter".
**INFO [authentication] Add globalResources value-converter: authFilterValueConverter.**

How can I resolved the following error:
Unhandled rejection Error: Cannot find module './aurelia-authentication/authFilterValueConverter'.
    at http://localhost:5000/bundle/1.bundle.js:249:42
    at webpackContextResolve (http://localhost:5000/bundle/1.bundle.js:249:90)
    at webpackContext (http://localhost:5000/bundle/1.bundle.js:246:30)
    at http://localhost:5000/bundle/bundle.js:7451:50
    at Function.requireEnsure [as e](http://localhost:5000/bundle/bundle.js:62:29)
    at http://localhost:5000/bundle/bundle.js:7450:32
    at WebpackLoader._import (http://localhost:5000/bundle/bundle.js:7445:13)
    at http://localhost:5000/bundle/bundle.js:7501:17
From previous event:
    at WebpackLoader.loadModule (http://localhost:5000/bundle/bundle.js:7499:13)
    at WebpackLoader.loadAllModules (http://localhost:5000/bundle/bundle.js:7485:24)
    at ViewEngine.importViewResources (http://localhost:5000/bundle/bundle.js:28172:25)
    at http://localhost:5000/bundle/bundle.js:18524:24
From previous event:
    at loadResources (http://localhost:5000/bundle/bundle.js:18515:8)
    at http://localhost:5000/bundle/bundle.js:18592:15
    at next (http://localhost:5000/bundle/bundle.js:18472:31)
    at runTasks (http://localhost:5000/bundle/bundle.js:18478:11)
    at http://localhost:5000/bundle/bundle.js:18757:17
From previous event:
    at http://localhost:5000/bundle/bundle.js:18756:22
From previous event:
    at FrameworkConfiguration.apply (http://localhost:5000/bundle/bundle.js:18742:43)
    at Aurelia.start (http://localhost:5000/bundle/bundle.js:18359:22)
    at http://localhost:5000/bundle/bundle.js:136:14
    at http://localhost:5000/bundle/bundle.js:240:13
    at Array.<anonymous> (http://localhost:5000/bundle/bundle.js:169:20)
    at http://localhost:5000/bundle/bundle.js:230:28
From previous event:
    at http://localhost:5000/bundle/bundle.js:222:45
From previous event:
    at run (http://localhost:5000/bundle/bundle.js:217:25)
    at Object.<anonymous> (http://localhost:5000/bundle/bundle.js:244:2)
    at Object.<anonymous> (http://localhost:5000/bundle/bundle.js:245:31)
    at __webpack_require__ (http://localhost:5000/bundle/bundle.js:48:30)
    at Object.<anonymous> (http://localhost:5000/bundle/bundle.js:106:39)
    at **webpack_require** (http://localhost:5000/bundle/bundle.js:48:30)
    at Object.<anonymous> (http://localhost:5000/bundle/bundle.js:98:19)
    at **webpack_require** (http://localhost:5000/bundle/bundle.js:48:30)
    at http://localhost:5000/bundle/bundle.js:91:18
    at http://localhost:5000/bundle/bundle.js:94:10

**Comment by doktordirk** [comment]
have you added it to the webpack build resources. in the current skeleton that's in package.json:

``` js
  "aurelia": {
    "build": {
      "resources": ["aurelia-authentication/authFilterValueConverter"]
    }
  },
```

**Comment by vinny-Jo** [comment]
how do you defined a webpack resources (in your documentation it does not mentioned it). in My webpack.config.js have got the following 

```
 plugins: [
        new AureliaWebpackPlugin({
            includeSubModules: [
                {
                    moduleId: 'aurelia-authentication'

                }
            ]
        }),
        new ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            'Promise': 'bluebird'
        })
    ],
```

**Comment by doktordirk** [comment]
yeah, that's with the 1.0.4 plugin: there it's as you posted. can you check with version of aurelia-plugin-webpack you use?

**Comment by vinny-Jo** [comment]
in my package.json have got the following dependencies:

"aurelia-authentication": "^3.0.0-rc5",
    "aurelia-bootstrapper-webpack": "^1.0.0-rc.1.0.0",
    "aurelia-event-aggregator": "^1.0.0-rc.1.0.0",
    "aurelia-fetch-client": "^1.0.0-rc.1.0.0",
    "aurelia-framework": "^1.0.0-rc.1.0.1",
    "aurelia-history-browser": "^1.0.0-rc.1.0.0",
    "aurelia-loader-webpack": "^1.0.0-rc.1.0.0",
    "aurelia-logging-console": "^1.0.0-rc.1.0.0",
    "aurelia-pal": "^1.0.0-rc.1.0.0",
    "aurelia-pal-browser": "^1.0.0-rc.1.0.0",
    "aurelia-polyfills": "^1.0.0-rc.1.0.0",
    "aurelia-route-recognizer": "^1.0.0-rc.1.0.0",
    "aurelia-router": "^1.0.0-rc.1.0.0",
    "aurelia-templating-binding": "^1.0.0-rc.1.0.0",
    "aurelia-templating-resources": "^1.0.0-rc.1.0.0",
    "aurelia-templating-router": "^1.0.0-rc.1.0.0",
    "aurelia-webpack-plugin": "^1.0.0-beta.4.0.0",

**Comment by doktordirk** [comment]
so with 4 it'll be as i said above. but problem is the the plugin 4 is bugged and not working with authentication yet. 

so atm best would be to

`npm i aurelia-webpack-plugin#1.0.4`

and keep the setting you posted above

**Comment by vinny-Jo** [comment]
apply the specific version. It is working but on the aurelia console (debugging I am still getting the following)
INFO [authentication] Add globalResources value-converter: authFilterValueConverter

where can I add the authFilterValueConverter?

**Comment by doktordirk** [comment]
that's just an info saying it just did that (added the value converter). so all should be fine

**Comment by vinny-Jo** [comment]
thanks. it works fine now.
