### ISSUE TITLE
Importing spoonx/aurelia-api

### ISSUE THREAD

**Issue by joelcoxokc** [SpoonX/aurelia-authentication#215]
This breaks the CLI.

The fix is just changing all imports that reference `spoonx/aurelia-api` to `aurelia-api`

**Comment by joelcoxokc** [comment]
I am closing this issue because this is resolved on master, but not in the latest release

**Comment by doktordirk** [comment]
@joelcoxokc still, can you elaborate? what could have been broken. 
here is the updated readme/build https://github.com/doktordirk/aurelia-authentication/tree/std-build

anyways, if you have comments for the std-build PR https://github.com/SpoonX/aurelia-authentication/pull/214 i'd be happy to hear them
