### ISSUE TITLE
auth0 wihtout auth0-lock

### ISSUE THREAD

**Issue by srollinet** [SpoonX/aurelia-authentication#230]
Is it possible or planned to support auth0 without auth0-lock (using auth0.js or their API).
I would like to be able to use auth0 without their UI.

**Comment by doktordirk** [comment]
i don.t think we.ll implement it ourselves. but PRs are usually welcome :)

**Comment by pfurini** [comment]
Auth0 not in popup mode (redirect mode): maybe I'll PR something in the future, if a standard oauth2/openid flow isn't sufficient.. 
If you want to investigate more, I'm under the impression that a standard flow (already supported by aurelia-authentication) can be used with auth0 without their libraries. If, beside having back a proper auth token from them, you want more control, you can simply import auth0.js lib in your services and do whatever you want.
