### ISSUE TITLE
add ability to override getTokenFromResponse with custom method

### ISSUE THREAD

**Issue by ricbermo** [SpoonX/aurelia-authentication#231]
It'd be nice if we, developer, had the ability to override this method.
Recently I was playing a little with Aurelia and this plugin and used Nodal to get an API running. Nodal authentication controller returns the access_token like this:
`{
  "meta": {
    "total": 1,
    "count": 1,
    "offset": 0,
    "error": null
  },
  "data": [
    {
      "user_id": 1,
      "access_token": "360e4cb7d49051d1c0991a299921aca9",
      "token_type": "bearer",
      "expires_at": "2016-09-07T21:42:43.439Z",
    }
  ]
}`

I was trying to get the access token via `accessTokenProp: 'data', accessTokenName: 'access_token', accessTokenRoot = true` w/o success.
Maybe it is just me and I don't know how to set the config values properly.

Maybe just adding a isArray check

**Comment by doktordirk** [comment]
yeah, array might not work atm. i think our approach needs rethinking to make it more flexible in general.

**Comment by doktordirk** [comment]
@ricbermo would that work for you  https://github.com/SpoonX/aurelia-authentication/pull/232/commits/26edc37939c8d42a6d750c627b6ec663ff9787f8  ?

**Comment by ricbermo** [comment]
@doktordirk yes sir, it'd totally do the job, thank you

**Comment by doktordirk** [comment]
done
