### ISSUE TITLE
How to use aurelia-authentication with x-www-form-urlencoded token request?

### ISSUE THREAD

**Issue by alexknips** [SpoonX/aurelia-authentication#234]
Hi, I would like to use aurelia-authentication according to the oauth 2 standard. For requesting a token I need to issue a x-www-form-urlencoded token request.

I tried doing this by calling

```
this.auth.login(this.email, this.password, {headers: {'Content-Type': 'x-www-form-urlencoded'}})
```

Unfortunately, the content-type is overriden by the following code in aurelia-api.js.

```
if ((typeof body === 'undefined' ? 'undefined' : _typeof(body)) === 'object' && contentType) {
    requestOptions.body = contentType.toLowerCase() === 'application/json' ? JSON.stringify(body) : (0, _aureliaPath.buildQueryString)(body);
}
```

I know it is a different package but I feel that this issue is mostly related to aurelia-authentication. 

Thank you for both great packages.

**Comment by RWOverdijk** [comment]
Hello @alexknips, which version are you using?

**Comment by alexknips** [comment]
"aurelia-api": "npm:aurelia-api@^3.0.0-rc8",
"aurelia-authentication": "npm:aurelia-authentication@^3.0.0-rc8"

**Comment by doktordirk** [comment]
i think it needs to be for x.form
this.auth.login({email: this.email, password, this.password}, {headers: {'Content-Type': 'x-www-form-urlencoded'}})

(and same for signup afaik if that's used)

**Comment by alexknips** [comment]
The final solution is 

```
return this.auth.login({username: this.email, password: this.password, grant_type: "password"}, {headers: {'Content-Type': 'application/x-www-form-urlencoded'}})
```

By the way, I am using OpenIddict.

Thanks a lot.

**Comment by doktordirk** [comment]
glad it worked. i'll see that i update the docs for that at some stage

**Comment by ahedreville** [comment]
glad it worked.
