### ISSUE TITLE
No Documentation on rest service?

### ISSUE THREAD

**Issue by stefan-gisworks** [SpoonX/aurelia-authentication#238]
Is there any documentation, what a rest service should return on this.authService.login(credentialsObject)?
Returning the token does nothing in aurelia-authentication.

**Comment by doktordirk** [comment]
that's not the job of a rest api server, but of an identity server. that one will only handle signup/login/profile and give out tokens.. the rest server then needs the token to see if a user is allowed to access the api

as for the token itself, it's best with a jwt (though any token as such works) (http://jwt.io)

you can have a look at my sample project https://github.com/doktordirk/aurelia-authentication-loopback-sample

**Comment by RWOverdijk** [comment]
The rest api may also handle authentication. It has to return the configured token key.

> // The property from which to get the access token after a successful login or signup
> accessTokenProp = 'access_token';
> 
> **_From: http://aurelia-authentication.spoonx.org/baseConfig.html_**
