### ISSUE TITLE
OIDC Provider Needed?

### ISSUE THREAD

**Issue by MartinMason** [SpoonX/aurelia-authentication#240]
I've been working on integrating aurelia-authentication with an OpenId Connect (OIDC) provider, OpenIddict. The same issues I'm facing would also be experienced by anyone trying to integrate with IdentityServer. Integration with an OIDC provider is like integration with a Auth0 as it should and probably would be the only configured authentication provider in your solution. I've got it "working" in an example github repository, https://github.com/SoftwareMasons/aurelia-openiddict, if you ignore the unhandled rejected promise errors that appear in the browser console. You'd need to use a forked version of the aurelia-authentication lib available here, https://github.com/MartinMason/aurelia-authentication. Part of the issue is that I'm using a slightly modified version of the authService.logout method. 

With an OIDC provider, a call to the LogoutEndpoint is very similar to the AuthorizeEndpoint. One really should be displaying a popup window with the location.href property set to the logout url. If the OIDC is configured to require logout confirmation, the user would be prompted in the popup window and if confirmed, redirected to the post_logout_redirect_uri. On successful logout, the authentication cookie created by the OIDC on successful login would be deleted and the popup window closed.

What would be the best way to proceed with this enhancement? I'm thinking that the differences with an OIDC provider are significant enough, as with Auth0, that a new provider type is required.

Here's a related discussion in the aurelia-auth . https://github.com/paulvanbladel/aurelia-auth/issues/28
 Any thoughts?

**Comment by MartinMason** [comment]
#244 implemented - can see use of this feature with OpenIddict at https://github.com/SoftwareMasons/aurelia-openiddict

**Comment by doktordirk** [comment]
done
