### ISSUE TITLE
Redirect URI cross origin domain for Popup window (Web platform)

### ISSUE THREAD

**Issue by genadis** [SpoonX/aurelia-authentication#248]
In my use case aurelia-authentication plugin is part of application that is a widget running on different websites (domains).
For example the widget can run on website: `foo.com`, while the widget authentication and operation is performed against server running on `widget.com/api`.

From what I can tell, the [popup](https://github.com/SpoonX/aurelia-authentication/blob/master/src/popup.js) windows is waiting for redirect to the hosting website:
`PLATFORM.global.document.location.host` to close the popup window and continue to the Post step.

That requires that the redirectUri is always of the website the call originated from.
In my case the redirectUri is to different domain (to the domain of my server providing the widget service).

It would be great if there was a configuration option that would allow to specify comparing to redirectUri instead of:

```
if (this.popupWindow.location.host ===  PLATFORM.global.document.location.host
```

In fact, this is what is done in case of eventListener (mobile platform):

```
if (event.url.indexOf(redirectUri) !== 0) {
```

So I'm not sure why the different behavior. For mobile platfrom the popup window is compared against the redirectUri, but for web plarform it compared always to the `document.location.host`.

**Comment by doktordirk** [comment]
i've updated from the source. can you give it a try. maybe it fixes it for you

for jspm:
`jspm i aurelia-authentication=github:doktordirk/aurelia-authentication@test`
for npm:
`npm i github:doktordirk/aurelia-authentication#test`

**Comment by genadis** [comment]
Thank you for your response.
Testing it, unfortunately no.
Below are debug results of the `pollPopup`
website domain: localhost:9000
widget server domain: 127.0.0.1:8000
protocol of both: http
redirectUri: http://127.0.0.1:8000/api/auth/google

![debug](https://cloud.githubusercontent.com/assets/6747147/18402783/d1103e1a-76e9-11e6-89a5-e94ead5c98ae.png)

Breakpoint on line 168 is not reached after the provider redirects to the redirectUri. 
Below is screenshot of the popup (the "ok" is what my server returns on GET of the redirectUri).

![popup](https://cloud.githubusercontent.com/assets/6747147/18402968/dd0f4b9c-76ea-11e6-92b9-3bede6a0dba1.png)

Seems there is CORS issue?
Since I have control of what gets returned from the GET of the redirectUri I could return a script that does `postMessage()`. But it will require aurelia-authentication plugin to listen to it and respond with closing the popup and continuing to POST step.
Just a suggestion...

**Comment by doktordirk** [comment]
i'm not quite sure if i get your setup correctly. so, let's compare to the 'usual' setup:

the app runs on localhost:9000
it opens a popup which load the login page from https://accounts.google.com/o/oauth2/auth'
after login, google redirects to  localhost:9000?code=xxz
the popup gets closed by the app
the the app posts the code xyz to auth server 127.0.0.1:8000/auth/google
the auth server handshakes with google to confirm the  code xyz,
the auth server sends back a created token j.w.t to the app
the app is happy with having a shiny new token j.w.t

so, where does your setup differ? or where do you want it to differ?

**Comment by genadis** [comment]
the app runs on localhost:9000
it opens a popup which load the login page from https://accounts.google.com/o/oauth2/auth'
after login, google redirects to 127.0.0.1:8000/api/auth/google?code=xxz
the popup gets closed by the app (***Here is the issue)
the the app posts the code xyz to auth server 127.0.0.1:8000/auth/google
the auth server handshakes with google to confirm the code xyz,
the auth server sends back a created token j.w.t to the app
the app is happy with having a shiny new token j.w.t

If I set the redirectUri to localhost:9000 (window.local.host) as in the default and in the 'usual' setup, everything is ok and I've got the full setup working.
The thing is that in real life the app will run on hundreds or even thousands of websites so it's not practical to configure all those websites as allowed redirectUri.
So I need to configure single allowed redirectUri to my domain (127.0.0.1:8000 in the example above).

**Comment by doktordirk** [comment]
allowing blankly all redirectUrls would be a risk. does your auth server at least know all the domains?

**Comment by doktordirk** [comment]
so i guess your flow shoukd be
in popup:
Google redirects to your server
your server gets the webpage url from userdata which you can add to the popup
your server exchanges the code for a token  with google
your server checks the second redirecturl and redirects with the own token as parameter
the webpage sees that it got a token directly from the popup and uses that one

**Comment by doktordirk** [comment]
the last part is already in the ouths2.js code

**Comment by genadis** [comment]
Yes, Users cannon Authenticate (The POST step) just from any website.
Sorry for the long text below...

Regarding the flow You've described:
1. Google redirects to your server
2. your server gets the webpage url from userdata which you can add to the popup - You mean during the [POST](https://github.com/SpoonX/aurelia-authentication/blob/master/src/oAuth2.js#L72)? If so, yes that was my though as well. The GET (redirct inside the popup) is done by Google/Facebook/.... and the userData is not sent to the server so I cannot send the webpage url at that step, I surely cannot trust the referrer header as well.
3. your server exchanges the code for a token with google
4. your server checks the second redirecturl and redirects with the own token as parameter
5. the webpage sees that it got a token directly from the popup and uses that one

Not sure I understand what you mean in steps 4 & 5. I cannot perform the exchange of the code with token, authenticate the user and respond with jwt during the GET of the popup as mentioned in 2.

The full process (from redirect) I was thinking is:
1. Google/Facebook/... redirects to my server
2. My server gets the code from the redirect and generates response that includes script that will send `postMessage(). The data of the message could contain the full url as is (with the query parameters including the code)
3. The popup receives the message, checks the`redirecUri` if it matches, closes the popup and [resolves](https://github.com/SpoonX/aurelia-authentication/blob/master/src/popup.js#L71) with the data received from postMessage (parsed/validated as you see fit).
4. Oath2 takes it from here as usual performing the POST.
5. My server receives the POST (userData containing the webpage URL) with the code.
6. My server exchanges the code for a token with google/facebook/...
7. My server authenticates the user and responds with jwt token. 

Step 3 is the only missing puzzle peace. Something like this in popup.js:

```

pollPopup(redirectUri) {
     /* ... */
     this.polling = PLATFORM.global.setInterval(() => {
        /* ... */
     }, 500);

     // this is the addition, the rest is as is
     PLATFORM.global.addEventListener("message", (event) => {
            const origin = event.origin || event.originalEvent.origin;

             if (compareOriginWithRedirectUri(origin, redirectUri)) {

                   this.popupWindow.close();
                   PLATFORM.global.clearInterval(this.polling);

                   const params = parseUrl(event.data);
                   return params.error ? reject(new Error(params.error)) : resolve(params);
               }
       }, false);

       /* ... */
}
```

What do you think?

**Comment by doktordirk** [comment]
why contact you server twice? as the state makes a round trip, yuo can store the original url there, so, i'd still do like:

popup:
https://accounts.google.com/o/oauth2/auth ?
   redirect_uri=http://127.0.0.1:8000/auth/google &
   state=url%3Dhttp://localhost 
->
http://127.0.0.1:8000/auth/google ? 
   code=xyz &
   state=url%3Dhttp://localhost
(server checks url in the state, exchanges code for token with google and generates own jwt and redirect to url eg https://davidwalsh.name/express-redirect-301)
->
http://localhost ?
   token=xyz &
   state=url%3Dhttp://localhost
(popup closes and token is stored)

if you don't like it, maybe your own fork or extending aurelia-authentication in your app and try like

`` `js
Popup.prototype.pollPopup = function(redirectUri, serverUri) {
    return new Promise((resolve, reject) => {
      const redirectUriParser = DOM.createElement('a');
      redirectUriParser.href  = redirectUri;
      const redirectUriPath   = getFullUrlPath(redirectUriParser);

```
  this.polling = PLATFORM.global.setInterval(() => {
    if (!this.popupWindow || this.popupWindow.closed || this.popupWindow.closed === undefined) {
      PLATFORM.global.clearInterval(this.polling);

      return reject(new Error('The popup window was closed'));
    }
```

//------------------------------------
        try {
          const popupWindowPath = getFullUrlPath(this.popupWindow.location);

```
        if (popupWindowPath === serverUriPath) {
```

// get hash and stuff from popupWindow.location
               popupWindow.location.href = redirectUrl + hash and stuff
               return;
           }
//---------------------------------------
          if (popupWindowPath === redirectUriPath) {
            this.popupWindow.close();
            PLATFORM.global.clearInterval(this.polling);

```
        if (this.popupWindow.location.search || this.popupWindow.location.hash) {
          const params = parseUrl(this.popupWindow.location);

          return params.error ? reject(new Error(params.error)) : resolve(params);
        }

        return reject(new Error(
          'OAuth redirect has occurred but no query or hash parameters were found. ' +
          'They were either not set during the redirect, or were removed—typically by a ' +
          'routing library..'
        ));
      }
    } catch (_) {
      // Ignore DOMException: Blocked a frame with origin from accessing a cross-origin frame.
      // A hack to get around same-origin security policy errors in IE.
    }
  }, 500);
});
```

  }

```
```

**Comment by genadis** [comment]
Thank you for the suggestion regarding the usage of state query parameter and single query to the server.

The issue I'm facing is not solved by that.
When the popup is in different domain than the webpage, it is impossible to access the [popupWindowPath](https://github.com/doktordirk/aurelia-authentication/blob/test/src/popup.js#L68) of the `this.popupWindow.location` due to [browsers cross origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Location).

Please see the debug screenshot:
![debug](https://cloud.githubusercontent.com/assets/6747147/18412384/8a1e7164-7795-11e6-8cbb-28c4ce0f791e.png)

The breakpoint at 168 is never reached. and at breakpoint 166 notice the error at the console window.
The popup never closes...

It's a simple solution using the `window.postMessage()` interface. I could fork and implement it myself (basically it's the code I've pasted in previous comment).
But I'm sure more people will bump into this issue if they try to use the plugin in an application where webpage domain is different from the redirectUri.

**Comment by doktordirk** [comment]
if your server redirects then back to your webpage, than this shouldn't be a problem or? at least, i hoped/suggested it'll work like:

popup loads google page (popup keeps polling) -> redirect to server with code
popup loads (empty) server page (popup keeps polling) -> redirect to web app with jwt
popup loads web app page (server stops polling and close popup)

**Comment by genadis** [comment]
according to [this line](https://github.com/doktordirk/aurelia-authentication/blob/test/src/popup.js#L70) the popup will close only when the redirectUri is equal to the popup window.
The redirectUri is not the webpage, but the server which is different domain from the webpage (this is the issue). So if server will redirect to the webpage url it won't help...

I cannot set the redirectUri to webpage url because it will require configuring a lot of domains (all the websites the application runs on) as valid redirect uris (the issue I've describes and where the discussion has started :) )

Actually it might work in the main repository because [according to this line](https://github.com/SpoonX/aurelia-authentication/blob/master/src/popup.js#L64)  the popup will close when it's url is equal to the document.location and NOT the redirectUri. If you merge the test branch as it is, it will break it.
I think the behavior in the test branch is the correct one (comparing to the redirectUri), but it will actually limit this use case (unless you add the `postMessage()` functionality.

I'll test with the master branch of this repository and inform here...

**Comment by genadis** [comment]
Yep.. with version: npm:aurelia-authentication@3.0.0-rc9 it's working (quick test done with google and facebook providers).

But if you merge the test branch with the change of comparing to the redirectUri, it will break.

Please if you merge the test branch, add the listening to the `message` event functionality.

For reference, the setup that worked required the configuration (for the providers):

```
      optionalUrlParams: ['state'],
      state: window.location.origin
```

On server for quick test (nodejs - hapijs):

```
        if (request.method === 'get') {
            const url = decodeURIComponent(request.query['state']) + `?code=${request.query['code']}`;
            return reply.redirect(url);
        }
```

At the moment the exchange and authentication is done on POST. I'll test the whole process on the the GET as well.

**Comment by doktordirk** [comment]
great.
but what you need the messages for then?

ps: i'll just drop that update PR. seems the previous=current version makes more sense

**Comment by genadis** [comment]
If you are dropping [this](https://github.com/doktordirk/aurelia-authentication/blob/test/src/popup.js#L70):

```
if (popupWindowPath === redirectUriPath) {
    // ...
}
```

and staying with [this](https://github.com/SpoonX/aurelia-authentication/blob/master/src/popup.js#L64)

```
if (this.popupWindow.location.host ===  PLATFORM.global.document.location.host
            && (this.popupWindow.location.search || this.popupWindow.location.hash)) {
   //...
}
```

then there is not need for the messages.

Thank you for the patience and help!

**Comment by doktordirk** [comment]
i will. we can close this then.

**Comment by baconinthemorn** [comment]
I am having this same issue and have not been able to find a solution thus far. The pop up stays open for users when they are logging in via Google & only if they are not logged in to that provider already (completely logged out of Google itself and our application). 

On closer investigation, it looks to be `_this2.popupWindow.location.host` which is causing this error/exception to throw with an error message of:

**DOMException: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame.**

My application is configured using a singular OIDC provider (Identity Server 4) only leveraging External Providers (Google & Microsoft).

It looks like this was addressed, but doesn't seem be working correctly for me. Any insight as to why or how to overcome this obstacle is greatly appreciated. I will keep digging and see what I can discover or hopefully amend to get this working (literally the last piece of our puzzle).

**Comment by RWOverdijk** [comment]
@baconinthemorn I don't understand your question. Would you mind opening up a new issue with more information and an easier to follow problem?

**Comment by baconinthemorn** [comment]
Sure thing, I've created a new issue and added some additional information/image.

New Issue: #373
