### ISSUE TITLE
Refresh Token Incompatible with Django JWT

### ISSUE THREAD

**Issue by cb-fred** [SpoonX/aurelia-authentication#254]
Hi, I tried to refresh a jwt token on a django-rest-framework-jwt api, unfortunately the 
refresh payloads seem to be incompatible. 

The Django refresh route expects a post with the following JSON payload:

```
    {
         token: 'feafeaf...efea',
    }
```

However aurelia-authentication sends a 

```
    {
       grant_type: 'refresh_token',
       refresh_token: 'feafeaf...efea',
    }
```

Is there any way to modify the format of the updateToken() request payload to match what Django expects ?

**Comment by doktordirk** [comment]
oh well, since it's the last non-configurable, i guess it could/should be done. care to make a PR to that end?

**Comment by cb-fred** [comment]
Sure :)

**Comment by doktordirk** [comment]
merged https://github.com/SpoonX/aurelia-authentication/pull/255
