### ISSUE TITLE
Can't override baseConfig options?

### ISSUE THREAD

**Issue by nathanchase** [SpoonX/aurelia-authentication#259]
in the BaseConfig, the default for _loginUrl_ is as follows:
`this.loginUrl = '/auth/login';`

but if I try to override it in my authConfig to something else:

ex: `loginUrl: 'oauth2/token'`

it does not take effect.

What am I missing?

**Comment by nathanchase** [comment]
FYI, I am using:
"aurelia-api": "3.0.0-rc9",
"aurelia-authentication": "3.0.0-rc11".

Is this the current recommended release version to use for both packages?

**Comment by doktordirk** [comment]
versions are fine i think. no effect? weird. one might think the missing '/' cause trouble, but that would be an effect as well i.d say

**Comment by doktordirk** [comment]
else your authConfig works fine?

**Comment by nathanchase** [comment]
Yeah, I tried removing everything non-essential. This is my authConfig:

```
export default {
    endpoint: 'https://myapi.com',
    loginUrl: 'oauth2/token'
};
```

if I remove the loginUrl line, and move it to my main,js, it finds it (and replaces correctly) when it's done there:

```
...
.plugin('aurelia-authentication', baseConfig => {
        baseConfig.configure({
          loginUrl: 'oauth2/token'
        });
    });
...
```

So somehow the authConfig data is not getting added to the plugin.

I'm using aurelia + ES2016 + webpack, based off the skeleton.
https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack

**Comment by doktordirk** [comment]
the missing '=' is a copy/paste error?
anyways, try a named export

Yeah, I tried removing everything non-essential. This is my authConfig:

```
export let authConfig ={
    endpoint: 'https://myapi.com',
    loginUrl: 'oauth2/token'
};
```

``` js
import {authConfig} from 'authConfig';

/...

.plugin('aurelia-authentication', authConfig);
```

**Comment by ne0guille** [comment]
@doktordirk could you manage to fix this? im having the same issue here with both aurelia-auth and aurelia-authentication plugins

**Comment by ne0guille** [comment]
found the isssue, it was generated becasue im using typescript i could successfully import my authConfig calling the authConfig.default property

**Comment by RWOverdijk** [comment]
I like it when someone finds the solution before I can even read the question. Nice! :)

**Comment by RWOverdijk** [comment]
Closing this. If this is still an issue, feel free to comment or reopen.

**Comment by alfkonee** [comment]
@All where's the solution for this I'm still facing the same situation here

**Comment by ne0guille** [comment]
I'm using typescript, the fix depends on how you are exporting your config.
This did the trick for me with the default config.
//this is the baseConfig obj
export default config;

//main.ts
import * as authConfig from './authConfig';
    .plugin('aurelia-auth', (baseConfig: AureliaAuth.BaseConfig) => {
      baseConfig.configure(authConfig.default);
    })
