### ISSUE TITLE
Compile dont work

### ISSUE THREAD

**Issue by lpj145** [SpoonX/aurelia-authentication#284]
I try run gulp build, and found: [Error: Cannot find module 'transform-es2015-template-literals'] code: 'MODULE_NOT_FOUND' } transform-es2015-template-literals]

but, module have!
i try npm install and npm install babel-plugin-transform-es2015-template-literals

**Comment by lpj145** [comment]
Create .babelrc on path root.
and insert it:
`// without options
{
  "plugins": ["transform-es2015-template-literals"]
}`

**Comment by doktordirk** [comment]
hmm. but the travis.ci buikd works fine. try reinstalling the npm packages from scratch. like
`rm -rf ./node_modules && npm i`

**Comment by lpj145** [comment]
solved it with second comment.
