### ISSUE TITLE
Typings for authenticate method are incorrect

### ISSUE THREAD

**Issue by apawsey** [SpoonX/aurelia-authentication#294]
The documentation states the authenticate method has three parameters, the second of which is as follows:
`[redirectUri]  [string/0/null/undef ]  redirectUri overwrite. 0=off, null/undef=use default`
However the typing information just describes it as a string parameter.

I would suggest keep it as a string and just use an empty string, "", instead of 0, to indicate not a desire to not redirect anywhere.  Then it is simply an option string property...
- Not present = use default
- Present but empty = do not redirect
- Present = redirect to value supplied

**Comment by pfurini** [comment]
@apawsey I'm pretty sure that they are keeping that awkward parameters for backwards compatibility, so it's unlikely they'd change them as you suggested.

Beside that, you're right that typings should be fixed for the `authenticate` method. I know they'll refactor that method sooner or later, but current typings should reflect current signatures..

**Comment by doktordirk** [comment]
yes, that incredible stupid parameters are for backward compatibility. that's one of those things that has to get changed, once in some distant future we cancel full BC

**Comment by doktordirk** [comment]
hmm, empty string seems better. 'll do that
