### ISSUE TITLE
setTimeout event for token expiration doesn't fire if tab suspended or OS go to sleep

### ISSUE THREAD

**Issue by pfurini** [SpoonX/aurelia-authentication#295]
This is a known issue, and the reason why I prefer to use `setInterval` instead even if more expensive.
Another trick could be attaching a `window.focus` event listener, and check for token expiration there in addition to `setTimeout` handler.
If the OS goes to sleep, when it resumes the timeout has gone, but as soon as the user focuses the app window, you can check for token validity and correctly reset the session + redirect.
I'm experimenting this solution in my fork, if it works reliably I could push a PR if you're interested.

**Comment by doktordirk** [comment]
definatelly

**Comment by pfurini** [comment]
After a couple days of continued use, I can confirm that the focus trick is working well. At least with Chrome on OSX, I haven't had any chances to test with other browsers, let alone with other OSes..

Anyway I think it's an harmless fix, the only downside is having an additional handler that can potentially run multiple times on every focus change.. But given its small computational impact, it's a negligible overhead. I'll post the PR as soon as possible.

**Comment by doktordirk** [comment]
cool
