### ISSUE TITLE
Interceptor fails after refreshing token

### ISSUE THREAD

**Issue by diegograsso** [SpoonX/aurelia-authentication#302]
Hello, 
I have an error message in this line:
```return this.client.fetch(request).then(resolve);```
here:
https://github.com/SpoonX/aurelia-authentication/blob/master/src/fetchClientConfig.js#L69

fetch method fails because `client` is undefined but the interceptor is refreshing the token and working fine. I'm using `aurelia-api` 3.0.0
I noticed that this.client is always undefined inside the interceptor, but `this.httpClient` works fine.
So I solved my problem by replacing th previous line by:
```return this.httpClient.fetch(request).then(resolve);```

**Comment by doktordirk** [comment]
right. well spotted
