### ISSUE TITLE
Access Token question

### ISSUE THREAD

**Issue by rdehnhardt** [SpoonX/aurelia-authentication#310]
I have a problem when I log in via OAuth server.

My OAUTH server returns a JSON that looks like this:
{
"token_type": "Bearer",
"expires_in": 1296000,
"access_token": "MYTOKEN",
"refresh_token": "MYREFRESHTOKEN"
}

The problem is that the value being saved in the localStorage is the whole JSON and not only the access_token.

My Local Storage
aurelia_authentication -> {"token_type": "Bearer","expires_in": 1296000,"access_token": "MYTOKEN","refresh_token": "MYREFRESHTOKEN"}

How do I configure this?

**Comment by rdehnhardt** [comment]
This is my authConfig

export default {
    endpoint: 'auth',
    configureEndpoints: ['auth', 'protected-api'],
    loginUrl: 'oauth/token',
    redirectUri: 'dashboard',
    storageChangedReload: true,
    expiredRedirect: 1,
    clientId: 'MYCLIENTID',
    useRefreshToken: true,
    accessTokenProp: 'access_token',
    refreshTokenProp: 'refresh_token',
};

**Comment by RWOverdijk** [comment]
@rdehnhardt I didn't write that part so I'll have to check. I think it just stores the entire object, assuming it contains information you want to have (it's the response from the server after all).

**Comment by rdehnhardt** [comment]
Yes, but I need to store only the access token, because I need it for future API requests

**Comment by rdehnhardt** [comment]
This is the code that makes the access token storage?

https://github.com/SpoonX/aurelia-authentication/blob/master/src/authentication.js#L84

**Comment by RWOverdijk** [comment]
@rdehnhardt Why _only_ the access token? You can still get it. Is your question: _how do I get the access token_?

**Comment by vegafx12** [comment]
I was running into the same issue myself earlier... Based on the info in docs:

>     // The property from which to get the id token after a successful login
>     // idTokenProp: 'user_token',
> 
>     // If the property defined by `idTokenProp` is an object:
>     // -----------------------------------------------------------
>     // This is the property from which to get the token `{ "idTokenProp": { "idTokenName" : '...' } }`
>     // idTokenName: 'token',
> 
>     // This allows the id token to be a further object deeper `{ "idTokenProp": { "idTokenRoot" : { "idTokenName" : '...' } } }`
>     // idTokenRoot: false,

This configuration seems to indicate that setting these values will instruct the app to parse the token from the object itself? If so, I couldn't get it to do so. 

Do I need to configure interceptors to catch the response and parse it out manually?

True, the object is returned in the response and it can be handled, just not very "pretty" is all :(

**Comment by RWOverdijk** [comment]
@vegafx12 Sorry for the late response. I had a holiday and then turned out sick... 

Additional data is part of the payload in the token. I still don't fully understand the question I'm afraid.

**Comment by vegafx12** [comment]
@RWOverdijk I was just confused about some of the configuration settings mostly. The one thing that I believe @rdehnhardt was talking about (which I was also confused about), was the way the token is stored in local storage.

![image](https://cloud.githubusercontent.com/assets/16313950/22735743/aea67fee-edc0-11e6-8e27-f5ee782d6b1d.png)

If 'token' returned from server is an object. Is there code build into aurelia-auth to automatically handle this? I try passing just the value of the token object's property from server and aurelia-auth doesn't pick it up. Likely something I'm doing wrong, just wasn't sure if this was expected or not.

**Comment by RWOverdijk** [comment]
@vegafx12 The code implemented is the property you can pass in. It uses that to fetch the token. Storage isn't affected by this. The payload is in the token, part of it. The rest doesn't get stored.

**Comment by vegafx12** [comment]
@RWOverdijk In the screenshot on the aurelia-authentication homepage, you have this:

![image](https://cloud.githubusercontent.com/assets/16313950/22751607/ad39d158-edfa-11e6-9fbb-aa7a5752a688.png)

When I use aurelia-authentication, I get when you in my previous screenshot. Any idea what I might be doing differently?

**Comment by RWOverdijk** [comment]
That screenshot is very old. That was before we added support for refresh tokens.

It's still the same. The token contains the payload. I honestly don't see the issue. If you want to store more from the response, that's not in the payload, we'll have to find a solution for that. Is that your question?
