### ISSUE TITLE
Getting profile info from auth0

### ISSUE THREAD

**Issue by drewblas** [SpoonX/aurelia-authentication#314]
After successful login from auth0, is there any way to get access to the profile info?

The documented way to do this with auth0Lock is by calling `lock.getProfile(authResult.idToken)`.  I'm able to get the idToken from `authService.getTokenPayload()`.  But there is no access to the `lock` object.  It seems to be buried somewhere deep inside `authService.authentication.auth0Lock`.

The only alternative seems to be to re-construct the `auth0Lock` object myself. But this is problematic because I have to re-initialize it with the all the client config options all over again and it's quite redundant.

Possibly I'm going about this all wrong?

**Comment by RWOverdijk** [comment]
@drewblas You can use the `me` method for that. Tokens are used for authentication. You can get the payload itself, if that contains the data you need.

**Comment by larserikfinholt** [comment]
Hmmm... did you figure this out. Calling getMe()  on the AuthService does not call a 'me' endpoint at Auth0 (it calls my server). Do we need find the lock object and use that to get profile info, or are there maybe some config I've missed.

**Comment by RWOverdijk** [comment]
@larserikfinholt /me is for the server, yes. Otherwise you can use `.getTokenPayload()` https://aurelia-authentication.spoonx.org/api_authService.html

**Comment by jawa-the-hutt** [comment]
What I do is call the [/userinfo](https://auth0.com/docs/api/authentication#user-profile) Auth0 API endpoint.

That being said, you have to have the actual Auth0 access token in your possession to do this.  Currently, the Auth0 integration returns the id_token and calls it an access_token.  I've just submitted an [issue](https://github.com/SpoonX/aurelia-authentication/issues/397) to get feedback on proposed PR to address this.

if this PR gets submitted and approved it will mean a breaking change for the Auth0 integration, but it will give us additional features and abilities needed in working with the Auth0 API infrastructure.
