### ISSUE TITLE
login method in aurelia-authentication.d.ts is not same as in authService.js

### ISSUE THREAD

**Issue by evenlee** [SpoonX/aurelia-authentication#316]
I use aurelia-authentication to login locally, but when I try to use login code like [this](https://aurelia-authentication.spoonx.org/api_authService.html) example,
`this.authService.login({
  username: this.email,
  password: this.password,
  grant_type: "password"
}, {headers: {'Content-Type': 'application/x-www-form-urlencoded'}})  
  .then(response => {
    console.log(response);
  });`
 I got an error that the second parameter cannot convert to string. After some investigation, I found both ts and js  aurelia-authentication file in the dist folder have a different claim of the login method, which is:
`  login(emailOrCredentials: string|{}, passwordOrOptions?: string, optionsOrRedirectUri?: {}, redirectUri?: string): Promise<any> {`

but in the auService.js ,it is：

`  login(emailOrCredentials: string|{}, passwordOrOptions?: string|{},optionsOrRedirectUri?: {}, redirectUri?: string): Promise<any> {`

When I correct the ts and js file in dist folder, the error goes away, and my login works.
Please make a update for the two files in dist folder.

**Comment by RWOverdijk** [comment]
We haven't released this version yet. Are you working on master?

Either way, an update to v3.2.0 should fix things :)

**Comment by evenlee** [comment]
Yes, I used master to build my project, hope the new version coming soon:)

Sent from my iPhone

On Jan 13, 2017, 11:04 PM +0800, Wesley Overdijk <notifications@github.com>, wrote:

Closed #316<https://github.com/SpoonX/aurelia-authentication/issues/316>.

**Comment by RWOverdijk** [comment]
@evenlee Did you see the second sentence I wrote? I already published it :)

**Comment by evenlee** [comment]
My apologize, thanks, I will make the update:)

Sent from my iPhone

On Jan 14, 2017, 8:49 AM +0800, Wesley Overdijk <notifications@github.com>, wrote:

@evenlee<https://github.com/evenlee> Did you see the second sentence I wrote? I already published it :)
