### ISSUE TITLE
401's in aurelia-api are not redirecting to login via aurelia-authentication

### ISSUE THREAD

**Issue by ajoslin103** [SpoonX/aurelia-authentication#317]
I'm using aurelia-api v3.1.1 and aurelia-authentication v3.1.0 and calls to  aurelia-api endpoints that result in 401's are not redirecting to login via aurelia-authentication.

I'm using aurelia-authentication with simple username/password against my own backend -- I have a login page and a logout page.

my aurelia-api configs are as in the docs 

my authConfig is
```
	storageKey: (/localhost|local.host|0.0.0.0|120.0.0.1/.test(window.location.hostname)) ? 'localKey' : 'serverKey',
	configureEndpoints: ['auth', 'api', 'notes', 'history', 'ui'], // these want the bearer token
	endpoint: 'auth',
	loginUrl: 'login',
	loginRoute: 'login',
	storageChangedReload: true,    // ensure secondary tab reloading after auth status changes
	expiredRedirect: 1,            // redirect to logoutRedirect after token expiration
```

**Comment by ajoslin103** [comment]
whoops, my mistake -- the redirects are working as long as the calls are happening in code that is on a route

I have some code that runs in a static header, I'll have to catch errors in those and re-route myself

**Comment by RWOverdijk** [comment]
👍  for finding it yourself. That always makes me happy :D

**Comment by bennibeef** [comment]
Hmm, for me its not working. Might just be my mistake too but I don't know if I'm missing something.

I had an API call in a non-route but with it commented out it isn't working either. (don't know if this matters)
authconfig
```
          baseConfig.configure({
              endpoint: 'auth',
              loginUrl: '/login',
	      loginRoute: 'login',
	      storageChangedReload: true,
            //   loginRedirect: '/',
              authTokenType: 'JWT',
              configureEndpoints: ['auth', 'api'],
          });
```

And my API call is in route /#/tasks (constructor)

```
    this.apiEndpoint = config.getEndpoint('api');

    this.apiEndpoint.find('tasks')
      .then(tasks => {
        this.tasks = tasks;
        this.setupValidation();
      })
      .catch(console.error);
```

`GET http://localhost:3000/api/tasks 401 (Unauthorized)`
`Response {type: "cors", url: "http://localhost:3000/api/tasks", redirected: false, status: 401, ok: false…}`

Any ideas what I could be missing?

**Comment by RWOverdijk** [comment]
@bennibeef Did you configure the login redirect? https://aurelia-authentication.spoonx.org/baseConfig.html
