### ISSUE TITLE
logout() should work also if request to consif.logoutUrl fails

### ISSUE THREAD

**Issue by k2s** [SpoonX/aurelia-authentication#319]
I configured `logoutUrl`. In my project it is considered as normal, that the server is offline when user wants to logout. Currently the whole logout() process will fail and user is not able to logout. 

I think it should be at least configurable that server side logout is not guarantied if server is offline.

My quick workaround:

```
try {
      yield authService.logout()
    } catch (e) {
      authService.setResponseObject(null)
      window.location.reload()
    }
```

**Comment by RWOverdijk** [comment]
@k2s I suppose that makes sense. All our logout procedures are offline to begin with. I think that's why we didn't notice.

I think your workaround makes sense to just use though, what do you propose?

**Comment by k2s** [comment]
my workaround doesn't respect for example logoutRedirect

My suggestion is simple: https://github.com/SpoonX/aurelia-authentication/compare/master...k2s:patch-1

**Comment by RWOverdijk** [comment]
@k2s Open up a PR? :) I like it.
