### ISSUE TITLE
Always getting "Token not found in response"

### ISSUE THREAD

**Issue by suamikim** [SpoonX/aurelia-authentication#320]
Hi,

I'm currently trying to use the `aurelia-authentication` plugin with an already existing C# server infrastructure but can't get the login to work properly since I'm always getting an `Token not found in response` error.

I'm currently using the `aurelia-fetch-client` with the following base config:

```
let config = {
	baseUrl: 'https://127.0.0.1:446/',
	signupUrl: 'register',
	loginUrl: 'login',
	
	// Don't change hash on login/logout. Not needed since we switch shells...
	loginRedirect: undefined,
	logoutRedirect: undefined
};

export default config;
```

The server responds to my `login` request with status code `200` and some JSON which holds the user information including some user token which is later sent within the authentication header of every request which needs authentication.

The JSON looks something like this:

```
{
    email: "...",
    firstname: "...",
    lastname: "...",
    id: "....",
    userToken: "...."
}
```

I'd really appreciate some insights on how to properly form the response or change the config to get rid of the `Token not found in response` error.

Thanks & best regards

**Comment by suamikim** [comment]
Login is working if I change my server response to something like this:

```
{
    email: "...",
    firstname: "...",
    lastname: "...",
    id: "....",
    access_token: "...." // <-- "UserToken" in original response
}
```

Therefore I've tried to adjust my base config accordingly by adding a dedicated `accessTokenProp` setting:

```
let config = {
	baseUrl: 'https://127.0.0.1:446/',
	signupUrl: 'register',
	loginUrl: 'login',
	
	// Don't change hash on login/logout. Not needed since we switch shells...
	loginRedirect: undefined,
	logoutRedirect: undefined,

	accessTokenProp: 'userToken' // <-- This line is new
};

export default config;
```

Unfortunately this sole change (adding the `accessTokenProp`) leads to an unhandled exception on app start:

```
Unhandled rejection Error: Error invoking AuthService. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Token not found in response
Inner Error Stack:
Error: Token not found in response
    at Authentication.getTokenFromResponse (https://localhost:9000/scripts/vendor-bundle.js:27028:25)
    at Authentication.getDataFromResponse (https://localhost:9000/scripts/vendor-bundle.js:26967:145)
    at Authentication.setResponseObject (https://localhost:9000/scripts/vendor-bundle.js:26903:14)
    at AuthService.setResponseObject (https://localhost:9000/scripts/vendor-bundle.js:27229:27)
    at new AuthService (https://localhost:9000/scripts/vendor-bundle.js:27187:12)
    at Object.invoke (https://localhost:9000/scripts/vendor-bundle.js:12426:14)
    at InvocationHandler.invoke (https://localhost:9000/scripts/vendor-bundle.js:12379:168)
    at Container.invoke (https://localhost:9000/scripts/vendor-bundle.js:12643:25)
    at StrategyResolver.get (https://localhost:9000/scripts/vendor-bundle.js:12096:37)
    at Container.get (https://localhost:9000/scripts/vendor-bundle.js:12570:41)
    at Object.invoke (https://localhost:9000/scripts/vendor-bundle.js:12426:81)
    at InvocationHandler.invoke (https://localhost:9000/scripts/vendor-bundle.js:12379:168)
    at Container.invoke (https://localhost:9000/scripts/vendor-bundle.js:12643:25)
    at StrategyResolver.get (https://localhost:9000/scripts/vendor-bundle.js:12096:37)
    at Container.get (https://localhost:9000/scripts/vendor-bundle.js:12570:41)
    at Object.configure (https://localhost:9000/scripts/vendor-bundle.js:27706:49)
End Inner Error Stack
------------------------------------------------
```

**Comment by suamikim** [comment]
I'd really appreciate some help with this...

**Comment by RWOverdijk** [comment]
@suamikim Sorry, it has been a bit busy and I must admit I didn't see the notifications for this issue.

It can't find the token, so perhaps the accessTokenProp is broken. It's worth checking out why it's not being set. Would you mind taking a look and perhaps submitting a PR? The relevant code can be found around here: https://github.com/SpoonX/aurelia-authentication/blob/435e8b8898b6447b8d4b4ae49b6f18d0f42c777e/src/authentication.js#L211

Otherwise, I won't be able to look at this until (if I'm lucky) this weekend.

In case you can't, and you can wait, could you post an example response (JSON string) from your server here? That makes it easier to test.

**Comment by suamikim** [comment]
@RWOverdijk Thanks for pointing out the relevant part in the source! I'm not sure if I find the time to look into this myself this week but I'll try. If not, I can wait until you find the time ;)

The response from our server looks something like this:

```
{
    email: "...",
    firstname: "...",
    lastname: "...",
    id: "....",
    userToken: "...."
}
```

Please let me know if I can give you any more detailed information!

**Comment by RWOverdijk** [comment]
@suamikim That should work... Weird.

**Comment by suamikim** [comment]
I've finally found time to actually tackle this issue just to realize that adding `accessTokenProp: 'userToken'` to my config actually works as expected. I've no idea why it lead to an unhandled exception when I tried this 22 days ago (see [my earlier post](https://github.com/SpoonX/aurelia-authentication/issues/320#issuecomment-275038461))...

Thanks for the help either way!

**Comment by RWOverdijk** [comment]
Great news! Thanks for the update. Appreciate it!

**Comment by suamikim** [comment]
After a little more fiddling, I was now able to reproduce the above mentioned exception which actually had nothing to do with the config itself.

I'm using 2 different app shells for authentication & the main app and tried to set the correct shell on app start based on whether the user is already authenticated or not. I've tried to do this with the following code in `app.ts`:

```
import {Aurelia} from 'aurelia-framework'
// ...
import {AuthService} from 'aurelia-authentication';
// ...

export function configure(aurelia: Aurelia) {
	const auth = aurelia.container.get(AuthService);
	
	aurelia.use
		.standardConfiguration()
		.feature('resources')
		.plugin('aurelia-authentication', (baseConfig) => {
			baseConfig.configure(authConfig);
		});
	
	// ...
	
	aurelia.start().then(() => aurelia.setRoot(auth.isAuthenticated() ? 'main' : 'login'));
}
```

What actually triggers the exception is the line `const auth = aurelia.container.get(AuthService);` which instantiates the `AuthService`. I guess this fails due to the fact, that the `config` has not been applied correctly at the time it is called.

I'm not quite sure if this is intended behavior or a bug but I was able to work around it using the following code:

```
// ...
export function configure(aurelia: Aurelia) {
	aurelia.use
		.standardConfiguration()
		.feature('resources')
		.plugin('aurelia-authentication', (baseConfig) => {
			baseConfig.configure(authConfig);
			aurelia.setRoot(
				aurelia.container.get(AuthService).isAuthenticated()
					? 'main'
					: 'login'
			);
		});
	
	// ...
	
	aurelia.start(); // Don't call setRoot after the app start but after the auth plugin has been configured...
}
```

The thing is that I'm not quite sure if moving the initial `setRoot` away from the `start` promise resolution into the auth plugin configuration is some kind of bad practice or has any drawbacks.

I'd really appreciate some input on this!

**Comment by RWOverdijk** [comment]
I should mention that isAuthenticated is async. If it needs to refresh tokens for instance, the result will always be false. Best is to wrap it in a callback.

Another thing to note, is that you can use aurelia-config for this. You can find an example of the config here: https://github.com/SpoonX/swan-example-client/blob/master/src/scripts/main.js#L21,L30

aurelia-config allows you to easily configure plugins, in order of being defined. It also merges configs, making it easier to have a local configuration file.

**Comment by suamikim** [comment]
Thanks for the additional info! I'll definitely have a look at `aurelia-config` and use the callback.
I just realized one more thing:

The `Token not found in response` exception is also thrown, when initializing the `AuthService` on a machine which already has some authentication information saved in the local storage which differs from the apps current configuration.

E.g. I've already had some auth info saved in the local storage of my system at home. This auth info held the access token in the property `access_token` whilst my new config was looking for `userToken`.

I really think that this shouldn't happen since this exception effectively prevented the app from starting up correctly. Removing the existing auth info from the local storage "solved" the issue.

**Comment by RWOverdijk** [comment]
@suamikim That's something that I've seen happen as well, but only in dev. It might be nice to validate that in some way. I agree.

**Comment by nvtin** [comment]
Hi @RWOverdijk I know this issue is so long time and to fix it, I have to return token in response. But It's weird and it should not be like that.
When I call login function, the Authorization in header will be set after successful login.
So why we need to get token from response?

**Comment by doktordirk** [comment]
@nvtin can you explain your scenario again. the problem the other one had with using two different configurations seems rather special.

anyways, the whole original login response is saved in local storage in case there is additional information in there needed later.  in the normal scenario, one might open your aurelia app in a different tab and then aurelia-authentication uses the original response object in there to check the login status.

**Comment by nvtin** [comment]
@doktordirk  Thanks for your response.
I am using rails for backend. And in backend I use `devise` and `devise-jwt` to authenticate user.

When we request login api to backend, backend will authenticate user and the `Authorization` will be set to header.

Response now just is a user object. Example:
`{"id":1,"uuid":"6dbc1dd7-ccb4-4b35-af35-22ad3d0aef19","name":"Test","email":"abc@gmail.com","deleted_at":null,"created_at":"2018-05-19T07:53:19.299Z","updated_at":"2018-05-19T07:53:19.299Z"}`

In Frontent, aurelia-authentication plugin get the response from backend, it will check to get the token from the backend's response and raise the error 'Token not found in response'.

So to resolve it, the token must be included in response.

I just ask to know why dont we get the Authorization token from request header instead get it from response? Or something I was wrong in config.

Can you help me to figure out it?

Thank you so much

**Comment by doktordirk** [comment]
i see. well, using the header to return the token isn't done to often. this lib had the more common case in mind where the token is returned in the response. 
to make it work with with plugin you'd have to add an interceptor to the fetch client which extracts the token from the header an adds it to the response. 

```js
.plugin('aurelia-api', config => {
      config
        .registerEndpoint('auth', 'http://auth/endpoint')  ;
        
        let fetchClient = config.getEndpoint('auth').client;
        fetchClient.interceptors.push(
          {
           response: (response, request) => {
             // that's maybe applied to often. could use an if(needed) {..} else return response;
             return response.json().then(body => {
               
               // get token from header and add it to the body (needs tweaking)
               body.token = response.headers.token;

               return new Response(JSON.stringify(body));
             });
           }
        }
    });
```

**Comment by nvtin** [comment]
@doktordirk Hi guy. Thanks for your time to response this.
But the code didn't work anymore.
So I think I should custom the response from backend to sure that token will be included to response body.

Thank you.

**Comment by sondr** [comment]
> ```
> // ...
> export function configure(aurelia: Aurelia) {
> 	aurelia.use
> 		.standardConfiguration()
> 		.feature('resources')
> 		.plugin('aurelia-authentication', (baseConfig) => {
> 			baseConfig.configure(authConfig);
> 			aurelia.setRoot(
> 				aurelia.container.get(AuthService).isAuthenticated()
> 					? 'main'
> 					: 'login'
> 			);
> 		});
> 	
> 	// ...
> 	
> 	aurelia.start(); // Don't call setRoot after the app start but after the auth plugin has been configured...
> }
> ```
> The thing is that I'm not quite sure if moving the initial `setRoot` away from the `start` promise resolution into the auth plugin configuration is some kind of bad practice or has any drawbacks.
> 
> I'd really appreciate some input on this!

I just encountered the same problem, and it seems the configuration of the plugin is complete if you get the authservice after aurelia.start():

```
aurelia.start().then(() => { 
     const auth = aurelia.container.get(AuthService);
     aurelia.setRoot(auth.isAuthenticated() ? 'main' : 'login');
});
```
Or async/await version
```
await aurelia.start();
const auth = aurelia.container.get(AuthService);
await aurelia.setRoot(auth.isAuthenticated() ? 'main' : 'login');
```

Looks and feel a bit better than setting root inside the plugin, at least to me.

**Comment by RWOverdijk** [comment]
That does look better 👍
