### ISSUE TITLE
In case updateToken fails user should be redirect to expiredRedirect (from config)

### ISSUE THREAD

**Issue by bondib** [SpoonX/aurelia-authentication#321]
Currently, if updateToken fails (the refresh token by itself might not be valid anymore), it just logs an error.

I would expect that if config.expiredRedirect is set - in case the updateToken operation failed - the user will be automatically redirect out of the app (to what ever I set in config.expiredRedirect)

**Comment by RWOverdijk** [comment]
Sounds good to me. Would you mind making a PR for this?

**Comment by gregleon** [comment]
Any progress on this?

I've come up with something like this.
```
   AuthService.prototype.updateToken = function updateToken() {
    var _this11 = this;

    (...)

      this.client.post(this.config.joinBase(this.config.refreshTokenUrl ? this.config.refreshTokenUrl : this.config.loginUrl), content, this.config.getOptionsForTokenRequests()).then(function (response) {
          _this11.setResponseObject(response);
          if(_this11.getAccessToken()){
                _this11.authentication.resolveUpdateTokenCallstack(_this11.isAuthenticated());
          }else{
            if(_this11.config.expiredRedirect){
               PLATFORM.location.assign(_this11.config.expiredRedirect);
            }
            _this11.authentication.resolveUpdateTokenCallstack(Promise.reject("something here"));
          }
      }).catch(function (error) {        
        _this11.setResponseObject(null);
        if(_this11.config.expiredRedirect){
           PLATFORM.location.assign(_this11.config.expiredRedirect);
        }
        _this11.authentication.resolveUpdateTokenCallstack(Promise.reject(error));
      });
    }
```
Basically we redirect user to expiredRedirect if

- ``` .catch(function (error) ``` happens which pretty much means no new token, or

- ```   _this11.setResponseObject(response);  if(!_this11.getAccessToken()) ``` meaning we can't find token in response.

Any thoughts?

**Comment by RWOverdijk** [comment]
@gregleon That would probably be the best way to do it. Albeit not in the dist dir but in src, but I assume you knew that. If either of you is willing to PR this I'd be more than happy to merge it in. It would be a great addition; probably even a fix.
