### ISSUE TITLE
Providers parameters are not beeing setted

### ISSUE THREAD

**Issue by ne0guille** [SpoonX/aurelia-authentication#326]
Hello, im having some problems using google provider OAuth2 with aurelia-auth

```
`var configForDevelopment = {

    providers: {
         google: {
            redirectUri:'http://localhost:3000/auth/google/callback',
            clientId: '611325554483-l3ipiu04q5tdaed8j9uplav0h1r70dd7.apps.googleusercontent.com'
        }
    }
```
![image](https://cloud.githubusercontent.com/assets/15113782/22902435/c2cd7b9c-f213-11e6-98b0-102feff67717.png)

I;ve setted my client id with all the defaults options, but its not beeing set on the current obj, so i get a 400 Error: invalid_request

Missing required parameter: client_id

this is the generated url:

`https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=&redirect_uri=http://localhost:3000&scope=openid profile email&display=popup&state=1xy089s3sir4cu660oj4np14i"`
`

**Comment by RWOverdijk** [comment]
@ne0guille Does this help? https://github.com/doktordirk/aurelia-authentication-loopback-sample/blob/f07bd1b1270829e20c2e09543231906214eac2c8/client-ts/src/authConfig.ts

I know this repo has been used to test several implementations.

**Comment by ne0guille** [comment]
closing this as #259
