### ISSUE TITLE
Refresh token with auto renew & multiple tabs open may lead to infinite storage events between tabs and browser freeze

### ISSUE THREAD

**Issue by bondib** [SpoonX/aurelia-authentication#327]
In case you have multiple tabs open and you are using refresh tokens that get auto renewed, this may lead to infinite storage events between tabs which will lead to browser freeze.

You can detect this issue by seeing in the console log:
"Stored token changed event" **thousands of times** and the browser will freeze.

This occurs as the code below (from https://github.com/SpoonX/aurelia-authentication/blob/master/src/authService.js) wasn't intended (at least it seems to me like that) to handle auto refresh tokens:

```
storageEventHandler = (event: StorageEvent) => {
    if (event.key !== this.config.storageKey || event.newValue === event.oldValue) {
      return;
    }

    logger.info('Stored token changed event');

    // IE runs the event handler before updating the storage value. Update it now.
    // An unset storage key in IE is an empty string, where-as chrome is null
    if (event.newValue) {
      this.authentication.storage.set(this.config.storageKey, event.newValue);
    } else {
      this.authentication.storage.remove(this.config.storageKey);
    }
```

When using the auto refresh tokens feature, each browser tab will independently try to renew the token as it gets expired. As all tabs share (at this point) the same token, the expire/refresh token even will occur IN SOME CASES the same time.
The end result of this use case is that aur-auth, for each open tab, independtly sent a seperate request for refresh token and now has new token information and will locally update the local storage with the new token information.

This raises the above "storageEventHandler" code for all open tabs except itself.

So if Tab1 sets internally token "1" - Tab2 gets notified of storage change event with a token value of "1".
But Tab2 - gets this event only after internally it set its token to "2".
So Tab now raises storage change event in Tab1 with value of "1".

This in some cases will never end as now Tab1 (as it got a different token that what it has, received "1" but internally has "2") will internally now set it back to "1".
And Tab2 (as it got a different token that what it has, received "2" but internally has "1")
 will internally now set it back to "2"

And this will endless continue...

I suggest fixing this issue quickly by entirety removing this feature (syncing the token between tabs) in case the auto refresh token feature is used - as each tab will independently send a  refresh option and take care of itself.
Yes - a bit a waste - but at least it doesn't crash the browser...

If anyone has a better suggestion on how to resolve - please do.

**Comment by RWOverdijk** [comment]
I suggest we instead _change_ the behavior. If refresh tokens are enabled, we validate the token instead of changing it. That way each tab gets 1 event, instead of infinite events. Is that correct?

**Comment by bondib** [comment]
Yes - good idea. This way we still keep the functionality of automatically logging out the user if in a different tab the user logged out.

BTW, this issue is critical as the browser completely freezes after an hour if you have more than one tab open on your site

**Comment by RWOverdijk** [comment]
@bondib I understand, I was a bit occupied.

The earliest I can look at this implementation is this weekend, unless you're willing to amend your pull request? Then I can review, merge and publish it today.

**Comment by bondib** [comment]
Hi @RWOverdijk . Please take a look at my pull request.
Seems to be working well.

**Comment by RWOverdijk** [comment]
@bondib I did, and I already commented on it 12 minutes ago :)

**Comment by RWOverdijk** [comment]
Published in 3.4.1! :)

**Comment by bondib** [comment]
Cool, thanks!

**Comment by AdamWillden** [comment]
@RWOverdijk I'm running 3.4.1

Normally this issue appears to be fine but just a moment ago the browser (internet explorer) was hammering the CPU however I've not managed to replicate it again. I had two tabs open, closed the other tab but the CPU was still maxed.

IE's profiler showed me that it was hammering `this.updateAuthenticated()` which is called in `storageEventHandler = (event: StorageEvent) => {` 

Not got any good info to follow up on here yet so i don't expect any action from you - just reporting that the behaviour is still happening. If it happens again I'll do my best to provide more detail so we can look into it some more.

**Comment by AdamWillden** [comment]
FWIW we're not using refresh tokens.

**Comment by RWOverdijk** [comment]
@AdamWillden The `autoUpdateToken` option doesn't work for you?
