### ISSUE TITLE
Option to returnRoute

### ISSUE THREAD

**Issue by Bitfiddler** [SpoonX/aurelia-authentication#336]
Would it be possible to add an option to the login method where you could instruct the service to return to a page that it left because it needed a login?

So right now you can do:
this.routing.auth.login({
            username: this.userName,
            password: this.password,
            grant_type: "password"
        }, { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } },
            '#/some-pre-determined-uri'
        );

Could we have an option:
this.routing.auth.login({
            username: this.userName,
            password: this.password,
            grant_type: "password"
        }, { headers: { 'Content-Type': 'application/x-www-form-urlencoded' }},
             returnToLast: true );

So somehow the navigationInstruction would need to be cached with all of the urlParams and then returned to after the authentication succeeds.

**Comment by RWOverdijk** [comment]
That would be an awesome feature! Do you want to give it a go?

**Comment by Bitfiddler** [comment]
Currently I have a lot going on so I won't be able to familiarize myself with the code base enough not to submit a hack.  Currently I got this to work by replacing the plugin's authenticateStep with my own:

	import { inject } from 'aurelia-dependency-injection';
	import { Redirect } from 'aurelia-router';
	import { AuthService } from "aurelia-authentication";
	import { StateStore } from "./StateStore";

	@inject(AuthService, StateStore)
	export class SaveNavStep {
		authService: AuthService;
		commonState: StateStore;

		constructor(authService: AuthService, commonState: StateStore) {
			this.authService = authService;
			this.commonState = commonState;
		}

		run(routingContext, next) {
			const isLoggedIn = this.authService.authenticated;
			const loginRoute = this.authService.config.loginRoute;

			if (routingContext.getAllInstructions().some(route => route.config.auth === true)) {
				if (!isLoggedIn) {
					this.commonState.postLoginNavInstr = routingContext;
					return next.cancel(new Redirect(loginRoute));
				}
			} else if (isLoggedIn && routingContext.getAllInstructions().some(route => route.fragment === loginRoute)) {
				return next.cancel(new Redirect(this.authService.config.loginRedirect));
			}

			return next();
		}
	}

The only difference between mine and the stock one is that I inject a 'StateStore' object where I save the NavigationInstruction that requires authentication.

Then in my login viewModel, I inject this same StateStore (singleton) object and do something like this to log in:

	login() {
		var redirectUri = '#/defaultRedirectUri';

		if (this.commonState.postLoginNavInstr) {
			redirectUri = this.routing.router.generate(this.commonState.postLoginNavInstr.config.name,
								this.commonState.postLoginNavInstr.params,
								{ replace: true });
		}
		var credentials = {
			username: this.userName,
			password: this.password,
			grant_type: "password"
		};
		this.routing.auth.login(credentials,
			{ headers: { 'Content-Type': 'application/x-www-form-urlencoded' } },
			redirectUri
		).catch(e => {
			this.dialogService.open({
				viewModel: InfoDialog,
				model: ExceptionHelpers.exceptionToString(e)
			});
		});
	}; 

Not ideal, but it works ;-)  If there is higher priority stuff you're working on, I can get back to this in a week or so to see if I can work this out without making a mess of your code (I'm still fairly new to Aurelia and Js development in general).

**Comment by RWOverdijk** [comment]
Awesome, that's pretty much it. Best to move this to the "after login" part of the code that currently does a fixed redirect to what's in the config. We could reuse that configuration key / part of the code to implement this.

Currently I'm working on the [wetland tutorial](https://wetland.spoonx.org/Tutorial/setting-up.html) which is taking up much of my time. After that I have to look into issues, and finish a project plugin for wetland. I'll be at it for a bit so if you could tackle this that'd be awesome! :)

**Comment by Bitfiddler** [comment]
Sure I'll give it a go this weekend, will be a good opportunity to make my first open source contribution ;-)
