### ISSUE TITLE
Implement Multifactor Auth

### ISSUE THREAD

**Issue by nerdstrap** [SpoonX/aurelia-authentication#338]
This is a request for documentation, a forked implementation, or a how to guide for adding multifactor authentication hooks into this plugin.

**Comment by RWOverdijk** [comment]
@nerdstrap Multi factor authentication isn't part of this plugin, yet. But it would be cool.

I'd like to use this issue as a starting point for that.

As a first guess, I'd say use .login() and send along the secret to the server. In which case nothing has to change here.

**Comment by nerdstrap** [comment]
we are issuing a basic claim JWT after UID/password to initiate a challenge. once the challenge is successful, we issue a full claim JWT. we use setResponseObject to take advantage of this plugin from there on out...

**Comment by RWOverdijk** [comment]
Interesting approach. Do you have some resources? It would be nice to create a recipe in the cookbook that helps you set up mfa

**Comment by nerdstrap** [comment]
we have OpenLDAP and RSA Adaptive Authentication running in our network. the MFA pieces are all custom RSA SecurID and Authentify service integrations. I wrote a simple C# web api to manage all of the orchestration of those service calls... it's still a work in progress

**Comment by RWOverdijk** [comment]
Hm... Keep me posted on the progress, if you want. I'm curious.
