### ISSUE TITLE
LinkedIn Issue.

### ISSUE THREAD

**Issue by InfoInterns** [SpoonX/aurelia-authentication#342]
Hello guys,

we try to make an authentication to LinkedIn with this PlugIn. For this project we require a Authentication-Token from LinkedIn. So far we achieved to get the authorization-code, but thats it. We dont exactly know how to proceed with this Plugin, so we can exchange the code for the token. 
We have already built the right Request-Url, which gives us the Token. We opened it in the browser and it worked. But if we try to access it automatically by making a request from aurelia-authentification.js, we just get this;

![fehlermeldung](https://cloud.githubusercontent.com/assets/26484999/24091960/b814c734-0d4b-11e7-88fe-b9fdeb99da92.png)

As we see it, we need a client without CORS or anything else, that gets access to LinkedIn-server.
Or can someone tell us a diffrent way, of how to proceed, when we got the Auth-Code.

**Comment by RWOverdijk** [comment]
@InfoInterns For the record, logs from gitter:

> Wesley Overdijk @RWOverdijk mrt. 17 16:00
@InfoInterns https://github.com/doktordirk/aurelia-authentication-loopback-sample/tree/master/client/src
An example implementation with facebook and twitter I think
Example config for linkedin on this page: https://aurelia-authentication.spoonx.org/baseConfig.html
>
> InfoInterns @InfoInterns mrt. 17 16:04
> Thank you very much!
> We use the config already, but we will work us through the example
>
> Wesley Overdijk @RWOverdijk mrt. 17 16:04
> Good luck :grinning:
> @InfoInterns If you solve it, please do tell what you were missing
I'd like to add it to the FAQ

**Comment by InfoInterns** [comment]
@RWOverdijk
Hi there,
we solved our Problem with
            httpClient.configure(config => {
                config.withBaseUrl('https://api.linkedin.com/v1')    

                    .withDefaults({                                  
                        mode: 'no-cors',
                    })
We use Aurelia now to get the Authorization Code, send it to our Wildfly Servlet and get the Token, which is sent back to our Aurelia App with aurelia-authentication.
The Wildfly Server is important to store our Client Secret, which is needed to get the Token and should not be visible for the users
