### ISSUE TITLE
login method promise call always return null 

### ISSUE THREAD

**Issue by tneway** [SpoonX/aurelia-authentication#345]
It seems like this method return http 200 and I see the token object in the chrome dev tab but never get to the success instead error is display.   Would you please someone help on this?

```js
return this.auth.login(model,
   {
       method: 'POST',mode:'no-cors',
       headers: {'Content-Type': 'application/x-www-form-urlencoded'}},
            this.returnUrl
   )
      .then(() => {
          alert('lkjlkj');
          this.authenticated = this.auth.authenticated;   //never get on this 
        })
        .catch(err=>{
            alert(JSON.stringify(err)+"err"); //alway return this 
        });
```

**Comment by RWOverdijk** [comment]
Could you supply more information?

What response does your server send back? As in, the body. Does it contain the access_token?

**Comment by tneway** [comment]
yes, here is the response 
![capture](https://cloud.githubusercontent.com/assets/22864517/24513871/fb3efae0-1537-11e7-9cea-503ea8bfae41.PNG)

**Comment by RWOverdijk** [comment]
And login doesn't work? That's odd. What happens when you try this without the custom headers etc? (just as a test)

**Comment by tneway** [comment]
I got http 400 error with out a header

**Comment by RWOverdijk** [comment]
What kind of server are you using?

**Comment by tneway** [comment]
the back end is asp.net web api 2

**Comment by RWOverdijk** [comment]
I can't believe I didn't ask this earlier, but what is the error you're getting?

**Comment by tneway** [comment]
I already describe it in the comment above as you see in the post the token object is return from the server but the code on success (. then) never run but  alert(JSON.stringify(err)+"err");  see above

**Comment by RWOverdijk** [comment]
@tneway Yes, but what's the output of `alert(JSON.stringify(err)+"err");`?

**Comment by tneway** [comment]
nothing(not valid error displayed )... in the example above it display string 'err'

**Comment by RWOverdijk** [comment]
And if you don't stringify it? Just log err? There has to be an error of some sort

**Comment by tneway** [comment]
I did that and didn't see any thing

**Comment by RWOverdijk** [comment]
Okay I'm genuinely curious now. Is there an easy way for me to reproduce this? I have no asp.net experience.

**Comment by tneway** [comment]
the client side is just Aurelia Js, with node and webpack... I just configure the server to access the token from the webapi as you see the server return the data but some what the client promise is empty or return some invalid value

**Comment by RWOverdijk** [comment]
Yeah but of all the users that use this, this is the first time I see anyone complain about this behavior. I even have a functional example online (swan-example). So something in your setup is doing this, and I need to be able to reproduce it to find the issue.

**Comment by tneway** [comment]
the weird part is if I use the fetch client this.http.fetch(....) I can access the success result

**Comment by tneway** [comment]
but the same set up works  for signup(...) method so I am not really sure. but if you want to produce it get a free version of visual studio and just create web api from default template with individual account. You will do it in 5min and call that service from Aurelia webapp

**Comment by RWOverdijk** [comment]
@tneway I'll give it a go once I have more time. In the meantime, could you check what happens here: https://github.com/SpoonX/aurelia-authentication/blob/master/src/authService.js#L468 see if you get in the where, and if not in the catch.

And maybe more importantly check here: https://github.com/SpoonX/aurelia-api/blob/master/src/rest.js#L80

This is the place most likely responsible for this behavior.What's response.status? Is there a response.status at all? Do you get in the then there, or also in the catch?

This info will help a lot. More info is better (output, debug logs etc)

**Comment by rikgarner** [comment]
Same problem here  - my .net web api returns a block of JSON with a token but the response from authService.login is null

**Comment by rikgarner** [comment]
If I simulate the login code in my module I get the token back - i.e. if I post the credentials to the auth URL just using the httpClient, it works:
```
login(email,password){
    var creds ={};
    creds = {
        'email'   : email,
        'password': password
      };
      this.httpClient.post("http://localhost:59869/login", creds)
        .then(response=>{
            console.log("success logged " + response);
            return response;
        })
        .catch(err => {
            console.log("login failure");
            console.log(err);
        });
}
```
suggesting the authService,login method is swallowing the response somehow.
