### ISSUE TITLE
 'Content-Type': "application/x-www-form-urlencoded" not being sent over through API

### ISSUE THREAD

**Issue by vincentw56** [SpoonX/aurelia-authentication#350]
Looks like the headers might not be transmitted properly. Using the code below, it should send over the "content-type", but it isn't working. It use to work fine, but it doesn't work with the newest version. This causes issues with the refresh token and authentication.

```.registerEndpoint("token",
                        __API_BASE__,
                        {
                            headers: {
                                'Content-Type': "application/x-www-form-urlencoded"
                            }
                        })

**Comment by RWOverdijk** [comment]
@vincentw56 Are you sure this worked before?

I know we did some automation regarding content type, so that's probably where it's off.

**Comment by vincentw56** [comment]
Well, I never had to send over the content type when doing the authentication so I am pretty sure it worked before. I know have to set the headers like this:

```this.authService.login(creds, { headers: { 'Content-Type': "application/x-www-form-urlencoded" } })```

I never had to do that before. And it looks like the refresh tokens don't work anymore and they use to work fine. Is there another way I should be doing it?

**Comment by jamesond** [comment]
I can confirm it worked before.

**Comment by jamesond** [comment]
This looks like it was changed after 3.4.1. Thank you Wesley.

**Comment by vincentw56** [comment]
There is a new config entry that has replaced this. In the config, you would add this:

```defaultHeadersForTokenRequests: { 'Content-Type': "application/x-www-form-urlencoded" }```

That will send over any default header information with auth and refresh token requests.
