### ISSUE TITLE
Implement handling for using 'auth: false' in your app.js router

### ISSUE THREAD

**Issue by reft** [SpoonX/aurelia-authentication#352]
Would be neat if the user is redirected to 'logInRedirect' page if authenticated and trying to go to the log-in page which has auth: false' in app.js router config.

Currently you can go to auth:false pages when you're authenticated.

**Comment by reft** [comment]
Same with 'auth: true'.. User should be redirect to the log-in page if not authenticated and trying to reach 'auth:true' pages. 

Now i just thinks it gives a console error.

**Comment by RWOverdijk** [comment]
@reft It would be neat. But do you think that should be dictated by this plugin? Maybe it's wisest to implement that yourself with a step or something.

**Comment by reft** [comment]
@RWOverdijk Okey I will try and implement my own auth:false step :)

**Comment by reft** [comment]
made me own authentication step here: https://github.com/SpoonX/aurelia-authentication/issues/351
