### ISSUE TITLE
Should not call GetMe() if expired access & refresh OR expired acces/not expired refresh

### ISSUE THREAD

**Issue by reft** [SpoonX/aurelia-authentication#353]
Scenario 1:

User logs in and then leaves the page. When both the access and refresh token is expired user again visits the page. By now the access and refresh token is expired and he no longer is authenticated, however the user still has tokens in local storage. Because of this, aurelia auth tries to call GetMe() when it shouldn't, (action can only be called by authenticated users and therefore returns (Unauthorized).

Scenario 2:

Access token exp - 1 hour
Refresh token exp - 8 hour

User logs in and then leaves the page. After two hours user again visits the page. By now the access token is expired but the refresh token is still active and valid. Aurelia auth should first refresh the token and then call the GetMe() function. Currently aurelia auth does it in this order:
1. GetMe()
2. RefreshToken()
3. GetMe()
The first step should be removed.

**Comment by RWOverdijk** [comment]
@reft You're right. I've noticed this, too. Thank you for identifying the issue. 👍

**Comment by RWOverdijk** [comment]
I haven't looked into this yet. I didn't forget, either.

**Comment by RWOverdijk** [comment]
Okay now I _did_ forget.

I'm also a bit strapped on time so I have to ask you what priority this issue has for you, and if you're perhaps willing to PR a fix?

**Comment by reft** [comment]
@RWOverdijk For me no rush, its just an "esthetic" bug, I would probably say that My other issue about users coming back with an expired access token / not expired refresh should have higher priority:) Also im currently on a looong holiday;)

**Comment by RWOverdijk** [comment]
@reft What issue is that?

Enjoy your looong holiday! :)

**Comment by reft** [comment]
@RWOverdijk https://github.com/SpoonX/aurelia-authentication/issues/351
