### ISSUE TITLE
logoutOnInvalidtoken gives error if not logged in

### ISSUE THREAD

**Issue by emilast** [SpoonX/aurelia-authentication#354]
The recently added feature with a `logoutOnInvalidtoken` config setting is great but it gives an error if the `/auth/login` endpoint fails to authenticate the user because of invalid credentials and returns a 401. We then do an attempt to logout the user but since she is not logged in yet, we get an error:

```
vendor-bundle.js:1395 Unhandled rejection TypeError: error_1.json is not a function
    at Login.<anonymous> (http://localhost:9000/scripts/app-bundle.js:179:48)
...
```
I attempted to fix this by adding an extra `this.authService.authenticated` condition in the `fetchClientConfig.js` file:

```
if (this.config.httpInterceptor && this.config.logoutOnInvalidtoken && !this.authService.isTokenExpired() && this.authService.authenticated) {
     return reject(this.authService.logout());
}
```
and it seems to work.

Do you agree that this is a reasonable change?

/Emil

**Comment by RWOverdijk** [comment]
That's perfectly reasonable. If someone isn't logged in, they shouldn't be logged out. However, if someone isn't logged in, they _should_ be redirected to the login page (if the current page is protected, that is)

**Comment by emilast** [comment]
Yes, that's true and my suggested fix stops that from happening. Any idea how to accomplish that?

**Comment by RWOverdijk** [comment]
@emilast What happens then? Does it just do nothing? You describe a situation where it doesn't attempt to logout, which is good. But it shouldn't do nothing. What does it do? What's the behavior now?

I can't look into this atm, that's why I'm asking all these questions.

**Comment by emilast** [comment]
Well, with my fix I get a failed request to the resource that returns a 401, but I'm not redirected to the login dialog. Maybe it would be better to move the "authenticated" check to inside the `logout()` function and only do the redirect part of that function if the user is not logged in?

**Comment by RWOverdijk** [comment]
I think that might be better. Thinking about it, doesn't the logout method also check if it _should_ redirect? If so, that's perfect because it then only redirects if the plugin was configured to do so.

**Comment by emilast** [comment]
@RWOverdijk Hi again, I just rolled back my local changes and don't get exactly the same errors as before, now it's just a bunch of these:

```
vendor-bundle.js:1395 Warning: a promise was rejected with a non-error: [object Object]
    at exports.FetchConfig._createClass.get.response (http://localhost:9000/scripts/vendor-bundle.js:40452:24)
...
```
Not sure what the difference is, so I'll have to dig into this a little more.

About the logic with redirection and other stuff in `logout()`, I have to confess I haven't grasped the full details about how it works. Redirection does work and I can live with the warnings in this case since it won't normally happen in my application. I'm good as long as I don't get errors.

I'll get back to you if I find something more regarding this behaviour.

**Comment by RWOverdijk** [comment]
Ack 👍

**Comment by emilast** [comment]
@RWOverdijk I have some more information now. I still have the problem (must have been a little bit confused earlier...).

The problem is this code (it's Typescript, not that it matters) that I use for showing my users the reason for failed login attempts:

```
this.authService.login(request)
  .catch((error: any) => {
    error.json().then(errorPayload => {
      this.errorMessage = errorPayload.Reason;
    });
  });
```

This works well for `logoutOnInvalidtoken: false` but not when setting it to `true`. The reason is that `error` is not a Response anymore but a Promise that resolves to `undefined`. Obviously the `json()` function therefore fails, giving my original error message.

I did not expect the behaviour of the `login()` function to change when setting the `logoutOnInvalidtoken` option and I think that maybe it shouldn't. A simple (?) fix would maybe be to not apply the new option's behaviour when logging in?

**Comment by RWOverdijk** [comment]
I agree, that behavior sounds wrong to me, too. But I also can't believe it's the reason to be honest, unless the server, on login, returns an invalid token. Or did I not understand what you're saying?

**Comment by emilast** [comment]
The problem happens when attempting to *log in* using this sequence:

1. Collect credentials in my login form. 
2. Call `this.authService.login(request)`
3. If the credentials are invalid (e.g. wrong password) the server replies with a 401
4. a. If `logoutOnInvalidtoken: false`: I get a rejected promise with a Response object that I can call `json()` on to the details.
b. If `logoutOnInvalidtoken: true`: we get a rejected promise with `undefined`

The problem is that I don't get the same data in the rejected promise in the two cases.

**Comment by RWOverdijk** [comment]
Gotcha! Sorry for not following, I've been a bit distracted.

So now that I follow, yes, you get here: https://github.com/SpoonX/aurelia-authentication/blob/d44b7aef87c04cebbfe673df1d1d341578fb7714/src/fetchClientConfig.js#L57

Maybe, what makes most sense, is at the top of that interceptor method:

```js
if (!this.authenticated) {
  return reject(response);
}
```

You're not authenticated, and a request failed (otherwise the first conditional that checks property `ok` would have returned), so it's none of the interceptor's business.

Thoughts?

**Comment by emilast** [comment]
Yes maybe. I tried with replacing line 57 (`return reject(this.authService.logout());`) with this:

```
if (this.authService.authenticated) {
  return reject(this.authService.logout());
} else {
  return reject(response);
}
```
and it seems to work. Your suggested fix will also take of my problem but it's hard for me (being new to this JWT stuff) to see if it would have any ill side effects on the other logic in that function.

Doing the authenticated check as far down as possible in the decision tree limits the risk of the change causing trouble, but if you're sure it's okay to have it at the top of the interceptor function then why not?

**Comment by RWOverdijk** [comment]
@emilast It won't. If auth fails and there's no active identity, there's nothing to do for the interceptor. It'd have to be tested but I'm pretty sure that'll work. If you _are_ authenticated, it'll fail further down.

**Comment by emilast** [comment]
Ok, sounds good then. How do we go forward? The change is minor and I could do a pull request with it, but I had some initial trouble setting up my Windows machine for running the tests. Should be possible if I spend some time on it, I guess. Also, I suppose we should write a test that verifies the fix?

Being unused to collaborating on open source projects, what's the process for pull requests? I create a fork, do the fix and create a pull request that you accept?

**Comment by RWOverdijk** [comment]
@emilast that's correct :) And then I'll have someone look at it and test it more in-depth.

**Comment by RWOverdijk** [comment]
@emilast that's correct :) And then I'll have someone look at it and test it more in-depth.

**Comment by emilast** [comment]
Ok, I'll try then. Hopefully you can expect a PR in a day or two :-)

**Comment by RWOverdijk** [comment]
Awesome! Looking forward to it. Thanks :)

**Comment by RWOverdijk** [comment]
@emilast Is this working for you? It's in the latest release which seems to be working fine for me.

**Comment by emilast** [comment]
Sorry for the delay (I'm on summer vacation) but I have tested this now and it works correctly in 3.7.0. 👍
