### ISSUE TITLE
OpenId authService.authenticate(...) does not show popup on Safari, Mac and IPhone

### ISSUE THREAD

**Issue by chdev77** [SpoonX/aurelia-authentication#360]
Any hints on this?  My implementation works on PC Chrome and later Android devices.  Cannot get Safari working.

**Comment by RWOverdijk** [comment]
What version of safari is this? Maybe it's blocking the popup

**Comment by chdev77** [comment]
Yes it's blocking.  We tested from iPhone 5 and up. Nothing working.

**Comment by RWOverdijk** [comment]
I'm pretty confident this is something in your code.

Is the open a direct result of a user action?

You can find some common causes here: https://stackoverflow.com/questions/16559115/fb-login-popup-block
