### ISSUE TITLE
Feature request : role based authorization

### ISSUE THREAD

**Issue by zeko77** [SpoonX/aurelia-authentication#362]
Role based authorization seems like a cool feature and natural extension of this already excellent plugin.
1. **Authentication** is ensuring who you are
2. **Authorization** is what you can do

Currently, authorization is an obsolete version of authentication.
Maybe you could implement authorization as an optional pipeline step  that would check if user is in any of requested roles for the route.
I have followed your architecture and implemented it as step after authentication, together with value converter and all, and it works as a charm. It just pollutes my code a bit, so putting it here in plugin feels natural.
Best regards

**Comment by RWOverdijk** [comment]
Something like this? https://github.com/SpoonX/aurelia-acl

**Comment by zeko77** [comment]
Indeed. Seems like elegant solution. I can see that you are working on docs section, but i'll try to figure internals out from source. Great work.

**Comment by RWOverdijk** [comment]
@zeko77 Yeah it's quite old but it just worked so it never got changed.

**Comment by shawty** [comment]
Actually, I meant to write a message on this previously in here, but it completely slipped my mind :-)

In the app I'm currently working on, we send the roles back in a JWT (Roles user data section), all I then do is add my "RoleStep" to the router config immediately after the auth step from the auth main lib.

```
import { AuthenticateStep } from "aurelia-authentication";
import { RoleStep } from "./libs/RoleStep";
```

then later on:
```
config.addPipelineStep("authorize", AuthenticateStep);
config.addPipelineStep("authorize", RoleStep);
```
The role step roles are contained in the router data as follows:

```
{ route: "home", name: "home", moduleId: PLATFORM.moduleName("./pages/home/home"), nav: true, auth: true, title: "Home", settings: { icon: "fa-home", roles: ['user','admin','foobar'...] } },
```

And the actual Role step looks like the following:
```
import { inject } from 'aurelia-dependency-injection';
import { Redirect } from 'aurelia-router';
import StorageService from "./StorageService";
import UserTokenService from './UserTokenService';

@inject(StorageService, UserTokenService)
export class RoleStep {
  private storage: StorageService = null;
  private userToken: UserTokenService = null;

  constructor(storage: StorageService, userToken: UserTokenService) {
    this.storage = storage;
    this.userToken = userToken;
  }

  run(routingContext, next) {

    let config = routingContext.config;

    if (config.settings == undefined) {
      return next();
    }

    if (config.settings.roles == undefined)
    {
      return next();
    }

    if (config.settings.roles.length === 0) {
      return next();
    }

    let authObject = this.storage.getObject("aurelia_authentication");
    if(authObject == null)
    {
      // there is no aurelia authentication object, so that must mean where not actually logged in
      // all we can do is just drop out to the next... I think anyway - TODO: check if we can do this better
      return next();
    }

    let userRoles = this.userToken.getRolesUsingToken(authObject.token);
    let pageRoles = config.settings.roles;

    let userRolesContainsPageRoles = userRoles.some(role => pageRoles.includes(role));

    if(!userRolesContainsPageRoles)
    {
      return next.cancel(new Redirect("403"));
    }

    return next();
  }

}
```
Now, yes, there are some things that could be done better. For instance this was written before I finished reading the AU-Auth docs, and so didn't know it had methods to get the JWT and/or it's payload among other things.

However, this works perfectly for us with dotnetcore.  We use the Msft JWT bearer to create the token, and tell it to add whatever roles we have in the DB for the user logging in.  When the token is sent back in normal flow, the MSFT JWT stuff automatically verify's the token, and we can use the normal "role" attribute on a controller action as expected.

With the addition of the role step above, we can also use those exact same roles that the server is using against our actual routed pages too.

Anyway, it's nothing special, feel free to add it if you want to.

I don't have time to do it as a full pull request, or join the project team to implement it, but if you do use it a little thanks in the credits wouldn't go amiss :-)
