### ISSUE TITLE
Allow handling of non-expired tokens when server returns 401

### ISSUE THREAD

**Issue by Lee-Nover** [SpoonX/aurelia-authentication#367]
https://github.com/SpoonX/aurelia-authentication/blob/0f80003a1194fcec5aa595af4a05e80035b5499c/src/fetchClientConfig.js#L64

If the server returns a 401, it shouldn't matter if the token is expired or not; the server doesn't allow the token anymore so we should refresh.
Should be ok to just remove the check for token expiration in this line, like so:
```javascript
if (!this.config.httpInterceptor /*|| !this.authService.isTokenExpired()*/) {
```

**Comment by RWOverdijk** [comment]
I don't think that has to be true. It could be that we don't have access to the resource and the server utilizes a wrong status code. Regardless, this wouldn't affect your flow and eventually give you what you expect.

Or am I missing something here?

**Comment by doktordirk** [comment]
option has been added
