### ISSUE TITLE
Extend error with Typescript

### ISSUE THREAD

**Issue by jmdavid** [SpoonX/aurelia-authentication#369]
I followed the instructions but as soon as I add this:
`.plugin('aurelia-authentication', baseConfig => {
      baseConfig.configure(authConfig);
  });`
I get "TypeError: extend_1.default is not a function".

Thanks for help.

**Comment by jmdavid** [comment]
I forgot to  mention: here is my authConfig.ts:

`
import extend from 'extend';

var baseConfig = {
    endpoint: 'auth',
    configureEndpoints: ['auth', 'api'],
    loginRedirect: '/',
    logoutRedirect: '/',
    profileUrl: '/auth/me',
    withCredentials: true
};

var configForDevelopment = {
    providers: {
    }
};

var configForProduction = {
    providers: {
    }
};

var config;

if (window.location.hostname === 'localhost') {
    config = extend(true, {}, baseConfig, configForDevelopment);
}
else {
    config = extend(true, {}, baseConfig, configForProduction);
}

export default config;
`

**Comment by doktordirk** [comment]
sounds like aurelia-cli and adding all dependencies. see [https://aurelia-authentication.spoonx.org/installation.html]
