### ISSUE TITLE
Method 'updateAuthenticated' undefined

### ISSUE THREAD

**Issue by boshinski** [SpoonX/aurelia-authentication#370]
I'm getting errors "Object doesn't support property or method 'updateAuthenticated' thrown" when trying to execute the following lines in AuthService.js storageEventHandler method

```
    // in case auto refresh tokens are enabled
    if (this.config.autoUpdateToken && this.authentication.getAccessToken() && this.authentication.getRefreshToken()) {
      // we just need to check the status of the updated token we have in storage
      this.authentication.updateAuthenticated();
```

The problem is that there is no updateAuthenticated method defined in the Authentication class. Oddly enough, this has only manifested itself when executing in IE 11.

I'm using version 3.7.0

**Comment by RWOverdijk** [comment]
Seems related to the outcome in #339 

I've never had this issue before, but I think I see the problem.

https://github.com/SpoonX/aurelia-authentication/blob/master/src/authService.js#L91

I think this should be `this.updateAuthenticated();`

Would you mind testing that, and if it works submitting a PR?

**Comment by boshinski** [comment]
I'm not sure I understand your answer. You say that:

> I think this should be this.authentication.updateAuthenticated();

When that's what it currently is and that's the problem. Since there is no updateAuthenticated() method on this.authentication. It was never defined in the Authentication class.

**Comment by RWOverdijk** [comment]
@boshinski Updated my reply. I copy pasted when I was busy and forgot to remove authentication.

**Comment by vincentw56** [comment]
I created a PR for this. I probably didn't do it right since this I am not 100% familiar with doing it.

I did make the change locally and tested this. It is fixed now. I was receiving the same error above, but after the change, it is working fine. I waited a couple of days to verify by leaving the app open and idle.

**Comment by doktordirk** [comment]
fixed now
