### ISSUE TITLE
Auth0 LockWidget Social Provider Redirect

### ISSUE THREAD

**Issue by wpearson4** [SpoonX/aurelia-authentication#371]
Using Auth0 Lock Widget in popup mode disallows a redirect to happen when authenticating via the social providers.  Upon stepping through the code I noticed `options.auth.redirect = false` being explicitly set when mode ='popup'.  Is there a limitation when redirecting away from the popup although Auth0 will handle the redirection from the social provider?

**Comment by RWOverdijk** [comment]
@wpearson4 I don't know, I haven't used that option myself. It should be easy enough to test for you if you already have it set up like this, right? Would you mind doing that?

**Comment by wpearson4** [comment]
Upon redirecting to the social login and the redirection back it seems authentication is not picked up

**Comment by RWOverdijk** [comment]
In that case I don't know. If you figure it out a PR would be much appreciated. This is currently not a priority for me, but maybe someone else wants to pick this up.
