### ISSUE TITLE
Popup not closing: DOMException blocked frame due to cross-origin

### ISSUE THREAD

**Issue by baconinthemorn** [SpoonX/aurelia-authentication#373]
I'm troubleshooting an issue with my implementation where the login popup window does not close and redirect the user.

This only occurs when the user selects an account which is not already logged in/authenticated to the provider (Google, in this case). If they are already logged in to the Google account, and select it, this behavior is not witnessed.

See below for example:

![auth-bug](https://user-images.githubusercontent.com/6394442/35343886-9776f004-00e0-11e8-99ae-668402b3381e.gif)

What's more peculiar, is that if the user closes the popup, and then re-opens it (via `this.authService.authenticate()`) the user is logged directly in without any sort of prompt.

In my investigation it seems to be relative to the `pollPopup()` function, specifically this snippet:
```
if (this.popupWindow.location.host ===  PLATFORM.global.document.location.host
            && (this.popupWindow.location.search || this.popupWindow.location.hash)) {
```
From what I can tell, it seems the value for `this.popupWindow.location.host` cannot be determined due to a cross-origin conflict.

My provider is OIDC (IdentityServer4) and I am using aurelia-authentication version 3.7.0. Any insight you can provide will be greatly appreciated. 

Please let me know if I can provide any additional information that may be useful/helpful.

**Comment by baconinthemorn** [comment]
Some additional info on what is showing in a console log for `popupWindow` when the popup is opened:

![popupwindow-domexception](https://user-images.githubusercontent.com/6394442/35353834-4de57858-00fd-11e8-9df3-a4d00302dfcc.PNG)

**Comment by RWOverdijk** [comment]
It looks like you're using localhost for both providers. The url needs to be different.

**Update:** I mean auth and the app itself are both running on localhost.
