### ISSUE TITLE
Support for not needing new update tokens

### ISSUE THREAD

**Issue by diegotroitino** [SpoonX/aurelia-authentication#374]
I'm using [OppenIddict-core](https://github.com/openiddict/openiddict-core) on server side. In the release 2.0.0.rc1 they _"went no longer issue a new refresh token when sending a grant_type=refresh_token token request"_ by default.

There is an option to support the previous behavior, but [in this issue](https://github.com/openiddict/openiddict-core/issues/462)  @PinpointTownes explain why that's the new default.

Would be nice if aurelia-authentication could support that

**Comment by RWOverdijk** [comment]
Support the new default you mean? I'm open to PRs!

**Comment by doktordirk** [comment]
done
