### ISSUE TITLE
Automatic logout if accesstoken expires in more than 24.85 days

### ISSUE THREAD

**Issue by sondr** [SpoonX/aurelia-authentication#375]
setTimout gets called right away if timeout exceeds int32 max value(2147483647).

In authService.js:
```
setTimeout(ttl: number) {
    this.clearTimeout();
    const expiredTokenHandler = () => {
      if (this.config.autoUpdateToken
        && this.authentication.getAccessToken()
        && this.authentication.getRefreshToken()) {
        this.updateToken().catch(error => logger.warn(error.message));

        return;
      }
      this.setResponseObject(null);

      if (this.config.expiredRedirect) {
        PLATFORM.location.assign(this.config.expiredRedirect);
      }
    };

    this.timeoutID = PLATFORM.global.setTimeout(expiredTokenHandler, ttl);
    PLATFORM.addEventListener('focus', () => {
      if (this.isTokenExpired()) {
        expiredTokenHandler();
      }
    });
  }
```

Change suggestion: 
`this.timeoutID = PLATFORM.global.setTimeout(expiredTokenHandler, ttl);`
To
`this.timeoutID = PLATFORM.global.setTimeout(expiredTokenHandler, Math.min(ttl, Math.pow(2, 31) - 1));`

Or throw an error if access token lifetime is too long.

**Comment by RWOverdijk** [comment]
I agree. Something like that could be a good idea. Let the handler take a look at the time remaining and then pick it up again.

Regardless, such a long timeout is a strange thing to do combined with refresh tokens and has no priority for me personally. But a PR would be more than welcome!
