### ISSUE TITLE
Page not reloaded on logout in another tab

### ISSUE THREAD

**Issue by ShauniArima** [SpoonX/aurelia-authentication#379]
When the `storageChangedReload` is set to `true` in the config file. There is no reload of pages that are opened in other tabs.
Is it possible to reload all the tabs on a `logout()` event?

**Comment by RWOverdijk** [comment]
@ShauniArima Not that I'm aware of. I know someone did something similar, but I can't remember the outcome.

**Comment by ShauniArima** [comment]
@RWOverdijk It seems like `storage` events are not triggered when the `logout()` remove the key in the storage...

**Comment by RWOverdijk** [comment]
Interesting. The next click should log the user out though, right?

**Comment by ShauniArima** [comment]
Yes the logout works fine but the others tabs are not reloaded. The user is redirected to the login page on the next token refresh.

**Comment by RWOverdijk** [comment]
Hm... If you find an answer to this, please do share.

**Comment by ShauniArima** [comment]
Yes, I will investigate. Thanks for your help!

**Comment by doktordirk** [comment]
the fix of https://github.com/SpoonX/aurelia-authentication/issues/327 causes this. the problem here was actually anticipated. maybe we'll find a better fix for #327
