### ISSUE TITLE
REQ: skipAuthorization

### ISSUE THREAD

**Issue by nathanchase** [SpoonX/aurelia-authentication#39]
I saw on the [sahat/satlelizer repo](https://github.com/sahat/satellizer/) that they have the ability to prevent the authorization token on a per request basis like so:

> **How can I avoid sending Authorization header on all HTTP requests?**
> 
> By default, once user is authenticated, JWT will be sent on every request. If you would like to prevent > that, you could use skipAuthorization option in your $http request. For example:
> 
> ```
> $http({
>   method: 'GET',
>   url: '/api/endpoint',
>   skipAuthorization: true  // `Authorization: Bearer <token>` will not be sent on this request.
> });
> ```

Is this something that could be added to aurelia-auth?

**Comment by RWOverdijk** [comment]
@nathanchase Aurelia-auth already has support for patching specific endpoints (not your question, but perhaps useful, I use it for our SSO server so I don't have this issue). For specific request, I advice simply ignoring the Authorization header server side, as it doesn't do any harm.

If that's really something you don't like, we accept PRs! :)
