### ISSUE TITLE
Consider supporting httpOnly cookie for storing token

### ISSUE THREAD

**Issue by gregoryagu** [SpoonX/aurelia-authentication#390]
I am no security expert.

But I am [told](https://stackoverflow.com/questions/50547403/what-is-the-workflow-for-validating-a-refresh-token-and-issuing-a-new-bearer-tok/50548272?noredirect=1#comment88107976_50548272) that using an httpOnly cookie is more secure than localStorage.

See also [this](https://stackoverflow.com/questions/50547403/what-is-the-workflow-for-validating-a-refresh-token-and-issuing-a-new-bearer-tok/50548272?noredirect=1#comment88107976_50548272)

Thoughts?

**Comment by doktordirk** [comment]
The server set tHr cookie and isn.t the point that client side scripts cannot access it? As i understood it, everything here is as usual. Additionally, the cookie is set by the server when requesting your token. Then, when eg refreshing the server additionally checks that cookie. There is nothing to do on the client side. It.s all server side

**Comment by gregoryagu** [comment]
Yes, you are correct - it is primary a server side thing.

However, there is one configuration item to be done on the client in order to get the cookie to be sent to the server with each request:

The fetch client needs to have `credentials: 'include',` set.  When I use the fetch client, I do this:

```
this.httpClient.configure((config: any) => {
			config
				.withDefaults({
					credentials: 'include',
					headers: {
						"Authorization": bearerToken
					}
				});
		});
```
But how do I configure the instance of the fetch client that Aurelia-orm is using?

**Comment by gregoryagu** [comment]
Ok, I found how to do this:

```
.plugin(PLATFORM.moduleName('aurelia-api'),
        config => {
            config
                .registerEndpoint('protected-api', ServiceConfig.serviceName, {credentials:'include'})
		})
```
