### ISSUE TITLE
Ability to change the login content payload

### ISSUE THREAD

**Issue by simeonoff** [SpoonX/aurelia-authentication#41]
- [x] It would be nice if we could specify the payload parameter keys for login authentication with local strategies. As of now the payload sent to the server is always `{email: email, password: password}`, while my server expects a username key as a parameter for authentication.

**Comment by simeonoff** [comment]
NVM Just saw that i can pass an entire object to the login function with all the parameters I want...

**Comment by RWOverdijk** [comment]
@simeonoff Sounds like you helped yourself! That's what I like to see. :)
