### ISSUE TITLE
Does this support Yammer OAuth 2?

### ISSUE THREAD

**Issue by empz** [SpoonX/aurelia-authentication#51]
Yammer has OAuth 2 authentication but I can't make it work.
https://developer.yammer.com/docs/oauth-2

Is it supported?
Do you have an example of how should I config?

Thanks

**Comment by doktordirk** [comment]
@emzero 
first, this repo is for the serverside flow type. client side flow is easier and doesn't need this. though maybe you can reuse some code. so, maybe tell what is your setup and what you wanna do

**Comment by empz** [comment]
Oh, ok. I'm confused then. I thought it was for the client-side flow since Aurelia is a client-side framework. Isn't the server-side flow supposed to be run in the server? How does this repo does this within Aurelia?

Anyway, I'm rewriting an ASP.NET MVC application in ASP.NET 5 with Aurelia. Currently the application uses the server-side flow to authenticate with Yammer (making HTTP requests in .NET and grabbing the code in the return URI).
I was hoping to ditch the server-side approach and just use the client-side since I'll be having an SPA in Aurelia.

The problem I'm facing is that after authorizing the app, Yammer redirects the browser to a specified return URL appending the token like this:
`https://[:redirect_uri]#access_token=[:access_token]`
But I never get the token. I think it's because aurelia bootstrapper starts the router and the #access_token part is ditched in the process.

Yammer OAuth docs here: https://developer.yammer.com/docs/oauth-2

**Comment by doktordirk** [comment]
http://localhost:9000/#/welcome/#access_token=5 seems to work. maybe just need the right redirect url
