### ISSUE TITLE
Fix SPA redirects

### ISSUE THREAD

**Issue by AdamWillden** [SpoonX/aurelia-authentication#52]
We should use `import {Redirect} from 'aurelia-router';` instead of using `window.location` for SPA redirects (as eluded to [here](https://github.com/SpoonX/aurelia-auth/pull/47#issuecomment-196046101)). This will:
- make things consistent (note the `loginRoute` configuration option)
- probably be safer by conforming to aurelia's routing methods. I don't know if the current method could break the application's location history in some way.
- allow new defaults to support pushstate enabled applications (which do not use hashes)

**Comment by RWOverdijk** [comment]
@AdamWillden I disagree. The browser will then not prompt you to save your password. Also, a reload could be good to decide which assets to load (or not load) in main.js. I did the same for our project, and it makes the login page load a lot faster (e.g. not load the stylesheets etc). I can see this being different when the login page / modal / popover is on the same page as the spa, but then it still won't prompt you to store your password.

**Comment by doktordirk** [comment]
valid point i guess. aurelia'll get a official reload option though soonish. maybe we revisit it then

**Comment by AdamWillden** [comment]
Ah I see, that's a fair reason, I did wonder when I saw it asked me for my password as previous SPAs I've done didn't ask and that explains the change in behaviour!

@doktordirk are you suggesting that this would help https://github.com/aurelia/router/issues/201

If there were an option made available via the router that resolves the issues @RWOverdijk describes it'd be nice to be able to use it.

**Comment by doktordirk** [comment]
yes
