### ISSUE TITLE
Add to REAMDE how this differs from paulvanbladel/aurelia-auth

### ISSUE THREAD

**Issue by AdamWillden** [SpoonX/aurelia-authentication#53]
I've asked the question myself and I've seen it asked at least twice since. Save yourselves some time and stick it in the README! 

See here for comments: https://gitter.im/SpoonX/Dev?at=56e7dd5e618c335373ebf2dc

---
## How this differs from 'paulvanbladel/aurelia-auth'

This repository was originally a fork of paulvanbladel/aurealia-auth. It was forked when the original repository was in a period of inactivity, and later made into a repository of it's own. As such we often get asked how this repository differs from the original. So, at the time of writing the differences are as follows:
- Provides the option to use endpoints, introduced by [spoonx/aurelia-api](https://github.com/SpoonX/aurelia-api), which simplifies API access. 
  - By using aurelia-api the developer can specify which endpoints require the authentication patch.
- TypeScript support added through the addition of d.ts (typescript definition) files
- Lots of bug fixes
- Refactored code to be more readable and performant

**Aside:** Public SpoonX repositories are open to the community and actively maintained and used by the SpoonX company. They follow a strict deploy cycle with reviews and follow semantic versioning. This ensures code quality control and long term commitment.

**Comment by AdamWillden** [comment]
@doktordirk @RWOverdijk I have updated the original post. Let me know if you have any comments, if there is anything to add, or if you'd prefer I removed anything.

Conversely if you think this is worded okay and it contains all the required facts I will create a PR to this effect in due course.

**Comment by doktordirk** [comment]
dunno about that last two.
 while probably right, the first implies vanblandel doesn't. true or not, dunno if it is on us to say. i could live with just 'strict'. 
the second should be a given
@RWOverdijk i guess, one could add 'company support' or 'actively used by spoonx company ensures whatever code quality/long term commitment   or something

**Comment by RWOverdijk** [comment]
@AdamWillden Nice suggestion!

@doktordirk  Agreed. I'd use "strict", too.

And yes, we can add that this is being used in production and has long-term support. It's now being used in three of our products, as well as two at the company I work at. It's here to stay :)

**Comment by AdamWillden** [comment]
So do you mean to change the first line to:
- Strictly maintained and developed (by multiple developers)

Is it fair to say the these repositories are "commercially supported" then or do you just want "company support" as stated. I'm not sure if there's a subtle difference in meaning there but "commercially supported" is the usual buzzword.

Is this post still desired following the name change from `aurelia-auth` to `aurelia-authentication`?

**Comment by RWOverdijk** [comment]
@AdamWillden This is the line he meant. "stricter" sounds like we're pointing fingers to Paul (feels offensive):

> All SpoonX repositories follow a stricter deploy cycle with reviews

Re "supported": That's a good question. I think "commercially supported" sounds fine. What do you think @doktordirk?

**Update**: Read over the auth / authentication question. Yeah, it has been renamed to avoid confusion and not get left behind in the search results. Things are changing in this module so it should be its own module :)

**Comment by doktordirk** [comment]
commercially supported = paid support available. if the 'how it differ' is skipped, then just

Public SpoonX repositories are open to the community and actively maintained and used by the SpoonX company. They follow a strict deploy cycle with reviews and follow semantic versioning. This ensures code quality control and long term commitment.

**Comment by RWOverdijk** [comment]
@doktordirk :+1: you're a freakin poet.

**Comment by doktordirk** [comment]
@AdamWillden perfect now, just as tds -> d.ts typo.
let's get it in then

**Comment by RWOverdijk** [comment]
Can we get this in? Or is it already in and did I miss it?

**Comment by doktordirk** [comment]
still not in

**Comment by RWOverdijk** [comment]
@AdamWillden Can we get this in pleeeaaase?

![](http://thehoopla.wpengine.netdna-cdn.com/wp-content/uploads/2012/10/cute-cat-1.jpg)

**Comment by AdamWillden** [comment]
I have a customer demo tomorrow morning and have been working through lunches. I'll do it immediately following the demo tomorrow I promise! ~11am GMT

**Comment by RWOverdijk** [comment]
Yaaaaay, the cute kitty worked!

**Comment by AdamWillden** [comment]
Fixed by #83

**Comment by MrChriZ** [comment]
Was this intentionally removed - it doesn't appear on the latest readme?

**Comment by MrChriZ** [comment]
Ah I see it just moved to here:https://aurelia-authentication.spoonx.org/
