### ISSUE TITLE
add migration guide from vanBlandel auth

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-authentication#54]
related to https://github.com/SpoonX/aurelia-auth/issues/53

**Comment by RWOverdijk** [comment]
Should be relatively easy... But... Don't we work ootb?

**Comment by alfkonee** [comment]
I wanted to ask if this still plans to merge it's awesome new features into vanblandel's repo or has it diverged too much to be merged

**Comment by doktordirk** [comment]
dunno. also might has it's own version already. anyways, if you wanna do it, go ahead of course

**Comment by doktordirk** [comment]
do we wanna have one or is the readme addition enough?

**Comment by RWOverdijk** [comment]
@doktordirk There's not really a migration guide. It just works. But I do think it's a good idea to write one that "optimizes" the usage :+1:

**Comment by doktordirk** [comment]
then feel freee :smile:

**Comment by doktordirk** [comment]
done
