### ISSUE TITLE
Azure Active Directory / ADAL.js

### ISSUE THREAD

**Issue by oising** [SpoonX/aurelia-authentication#59]
Given that Satellizer didn't support Azure AD, does your library inherit this limitation?

https://github.com/sahat/satellizer/issues/433
https://github.com/sahat/satellizer/issues/453

> From: Sahat Yalkabov [mailto:notifications@github.com]
> Sent: Friday, 10 July 2015 2:37 PM
> To: sahat/satellizer
> Cc: nigel-dewar
> Subject: Re: [satellizer] Azure AD ? (#453)
> 
> I have decided not to add Azure AD authentication after all. It was the most frustrating experience. Their single sign-on process is either broken or just so horribly unintuitive. I couldn't even get past sign in popup to get authorization code. The page kept redirecting back after clicking on my account to https://login.microsoftonline.com/common/reprocess?sessionId=....... And if I were to log out I couldn't get to sign-in at all. When I enter an email and press TAB to enter a password, it automatically tries to sign you in, it then redirects to microsoft login, after logging in there, it redirects me back to Azure login. And the cycle repeats.

**Comment by doktordirk** [comment]
underlying is still sahat/satellizer. so i guess so

**Comment by RWOverdijk** [comment]
Hello @oising 

I've glanced at the requirements for such an implementation, and can say that we're not likely to implement it any time soon. I did find this beauty for you: https://azure.microsoft.com/en-us/documentation/articles/active-directory-devquickstarts-angular/

It's for angular, sure, but could offer some help. If you want to take it on (if possible), we'd gladly accept PRs. We can also offer some sparring in our gitter channer :)

I'm closing this as I hope this answers your question. If not, please let me know!

**Comment by oising** [comment]
@RWOverdijk Thanks -- btw, I couldn't find any decent explanations here why you forked aurelia-auth -- what's different, really?

EDIT: never mind, I see https://github.com/SpoonX/aurelia-authentication/issues/53 mentions it

**Comment by RWOverdijk** [comment]
@oising Glad you helped yourself :) :beers:
