### ISSUE TITLE
auth vs settings.auth

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-authentication#60]
i don't like that auth is added to the route instead of config.auth as i think it's supposed  to be. breaking change, i know, but i'd still like it changed. could support both for some time

**Comment by RWOverdijk** [comment]
What do you mean?

**Comment by doktordirk** [comment]
turns out i meant settings(.auth)

http://aurelia.io/docs.html#/aurelia/router/1.0.0-beta.1.1.3/doc/api/interface/RouteConfig

**Comment by doktordirk** [comment]
closed as both authFilter and authPipelinestep are already optional. further tweaks can be implemented in permissions
