### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by meash-nrel** [SpoonX/aurelia-authentication#7]
spoonx/aurelia-api is injected in several files, but is not a listed JSPM dependency in package.json.

separately installing it is required.

Also you can remove the legacy "aurelia-http-client" dependency while you are in there, as I believe you solely rely on fetch client now.

**Comment by RWOverdijk** [comment]
@meash-nrel Yes, yes and yes. You're right on the money!

**Comment by RWOverdijk** [comment]
Would you mind submitting a PR if you have time? I'm currently working out some other repos!

If not, I'll do this later today or tomorrow
