### ISSUE TITLE
Break apart readme

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/aurelia-authentication#84]
The readme is waaaaay way too long. For a module of this size, I think it's best to break it up into smaller documents. I have two suggestions:
1. Put it in separate markdown files in the `doc/` dir
2. Put it in the wiki (which can also be managed through version control)

My preference is option 2, because the wiki is a decent place to put this.

**Comment by doktordirk** [comment]
let's wiki then

**Comment by RWOverdijk** [comment]
I think I'll write a book for this repo, too (like orm). Agree?

**Comment by doktordirk** [comment]
notification is minor, but yeah, all other three deserve one

**Comment by doktordirk** [comment]
done
