### ISSUE TITLE
Change how Access/Refresh token nesting works

### ISSUE THREAD

**Issue by AdamWillden** [SpoonX/aurelia-authentication#87]
Following #93 I wonder if we could change something else. The whole token nesting by using `Prop => Root => Name` is **more** than a bit sucky. Without reading the comments the options are unclear and the names don't flow Root isn't the root.

Anyone have a better solution? I considered a single property that represents the path `some.pathTo.theToken` but I'm not sure how easy that is to unwrap or if that is less flexible for some reason.

**Comment by AdamWillden** [comment]
I'm okay with closing this. Just a thought I'd share

**Comment by doktordirk** [comment]
what why. i think it's a good idea

**Comment by AdamWillden** [comment]
Any ideas for implementation? The simplest way is just to split the string using dots.

http://stackoverflow.com/questions/6491463/accessing-nested-javascript-objects-with-string-key

http://stackoverflow.com/questions/8817394/javascript-get-deep-value-from-object-by-passing-path-to-it-as-string

Someone crazy **could** choose to use a dot within a property name which would screw up the pathing. However I don't think we should cater for this initially. See if it ever comes up as a requirement and if so someone could submit a PR to make an option that is non-breaking by default.

**Comment by doktordirk** [comment]
i opt for dots

**Comment by RWOverdijk** [comment]
I'm not entirely convinced about this approach. If you nest more than one level, you're doing something weird in your API. If that's the case, I'd like to hear complaints about it so they can explain what this is needed for. I'd prefer to cater for the 99%, and see why the other 1% is having problems with this.

That being said, I wouldn't refuse the PR.

**Comment by doktordirk** [comment]
hmm. probably right. so basically just cut down the sample in the comments to no root and token direct child of root

**Comment by AdamWillden** [comment]
@RWOverdijk this suggestion isn't to allow more nesting (even though technically I guess it could). I'm suggesting this because having 6 options (3 for access, 3 for refresh) seems overkill, the names are confusing and the order is quirky (`Prop`, `Prop => Name` or  `Prop => Root => Name`). I'd rather have 2 options (1 for access, 1 for refresh) and if there is any nesting then dot notation is used.

Just to be clear I believe in most cases you would be picking a property from the root, or at most 1 level deep in the response. I am in complete agreement with you.  Hey, I'd be happy to have a single property and no nesting at all if you're game :-P

If we weren't to change this then I'd suggest we might consider renaming the nesting properties somehow.

**Comment by RWOverdijk** [comment]
Dots, or a general "root" property (for all responses). I'm game yo

**Comment by doktordirk** [comment]
i copied over the dot version from sattelizer. implemented here https://github.com/SpoonX/aurelia-authentication/pull/100
