### ISSUE TITLE
build 2.1.0 broken

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-authentication#98]
@RWOverdijk 

fix on build branch 

have look at https://github.com/SpoonX/aurelia-authentication/commit/4cfe33b4bc9afb55c39ba9295f0c6da918559ca8

and if it's fine i recommend changing master to dev, build to master (+default) and releasing 2.1.1

**Comment by doktordirk** [comment]
ps: tested in my sample

**Comment by doktordirk** [comment]
on second though: i'd recommend just to revert the last PR

**Comment by doktordirk** [comment]
oh man i'm stupid. that's just what i do on this branch.

**Comment by doktordirk** [comment]
i obviously didn't manage to hold be back, and github published the fix on this branch

**Comment by RWOverdijk** [comment]
@doktordirk After arguing with yourself for a bit, what's the verdict? :p

**Comment by doktordirk** [comment]
hehe. ähm. well, the 'build' branch is the last published on github now. hence, i recommend switching branches

**Comment by doktordirk** [comment]
fix https://github.com/SpoonX/aurelia-authentication/commit/4cfe33b4bc9afb55c39ba9295f0c6da918559ca8 and in https://github.com/SpoonX/aurelia-authentication/pull/100
